--더미데이터

--부서
INSERT INTO "C##ALLISWELL"."DEPARTMENT" (NO, NAME) VALUES (SEQ_DEPARTMENT_NO.NEXTVAL, '외과');
INSERT INTO "C##ALLISWELL"."DEPARTMENT" (NO, NAME) VALUES (SEQ_DEPARTMENT_NO.NEXTVAL, '내과');
INSERT INTO "C##ALLISWELL"."DEPARTMENT" (NO, NAME) VALUES (SEQ_DEPARTMENT_NO.NEXTVAL, '소아청소년과');
INSERT INTO "C##ALLISWELL"."DEPARTMENT" (NO, NAME) VALUES (SEQ_DEPARTMENT_NO.NEXTVAL, '피부과');
INSERT INTO "C##ALLISWELL"."DEPARTMENT" (NO, NAME) VALUES (SEQ_DEPARTMENT_NO.NEXTVAL, '안과');
INSERT INTO "C##ALLISWELL"."DEPARTMENT" (NO, NAME) VALUES (SEQ_DEPARTMENT_NO.NEXTVAL, '치과');
INSERT INTO "C##ALLISWELL"."DEPARTMENT" (NO, NAME) VALUES (SEQ_DEPARTMENT_NO.NEXTVAL, '정신과');
INSERT INTO "C##ALLISWELL"."DEPARTMENT" (NO, NAME) VALUES (SEQ_DEPARTMENT_NO.NEXTVAL, '물리치료과');
INSERT INTO "C##ALLISWELL"."DEPARTMENT" (NO, NAME) VALUES (SEQ_DEPARTMENT_NO.NEXTVAL, '산부인과');
INSERT INTO "C##ALLISWELL"."DEPARTMENT" (NO, NAME) VALUES (SEQ_DEPARTMENT_NO.NEXTVAL, '응급의학과');

--POSITTION
INSERT INTO POSITION (NO, NAME, SALARY) VALUES (SEQ_POSITION_NO.NEXTVAL, '교수', 90000000);
INSERT INTO POSITION (NO, NAME, SALARY) VALUES (SEQ_POSITION_NO.NEXTVAL, '레지던트', 70000000);
INSERT INTO POSITION (NO, NAME, SALARY) VALUES (SEQ_POSITION_NO.NEXTVAL, '펠로우', 50000000);
INSERT INTO POSITION (NO, NAME, SALARY) VALUES (SEQ_POSITION_NO.NEXTVAL, '인턴', 30000000);
INSERT INTO POSITION (NO, NAME, SALARY) VALUES (SEQ_POSITION_NO.NEXTVAL, '부장간호사', 70000000);
INSERT INTO POSITION (NO, NAME, SALARY) VALUES (SEQ_POSITION_NO.NEXTVAL, '과장간호사', 60000000);
INSERT INTO POSITION (NO, NAME, SALARY) VALUES (SEQ_POSITION_NO.NEXTVAL, '수간호사', 50000000);
INSERT INTO POSITION (NO, NAME, SALARY) VALUES (SEQ_POSITION_NO.NEXTVAL, '주임간호사', 40000000);
INSERT INTO POSITION (NO, NAME, SALARY) VALUES (SEQ_POSITION_NO.NEXTVAL, '간호사', 30000000);

--MEMBER
INSERT INTO 
MEMBER
(NO, DEPARTMENT_NO, POSITION_NO, ID, PASSWORD, NAME, STATUS, POSITION_TYPE, ENROLL_DATE, REGISTRATION_NUMBER, EMAIL,  PHONE_NUMBER, OFFICE_NUMBER, LICENSE_NUMBER, YEAR_SALARY, PROFILE)
VALUES
(SEQ_MEMBER_NO.NEXTVAL, 1, 1, 'user01', 1234, '김의사', 'O', 'D', SYSDATE, '701012-1000000', 'a@alliswell.com', '01057963553', '0000000', '123-98-1111', 108000000, '외과의사.png');
INSERT INTO
MEMBER
(NO, DEPARTMENT_NO, POSITION_NO, ID, PASSWORD, NAME, STATUS, POSITION_TYPE, ENROLL_DATE, REGISTRATION_NUMBER, EMAIL,  PHONE_NUMBER, OFFICE_NUMBER, LICENSE_NUMBER, YEAR_SALARY)
VALUES
(SEQ_MEMBER_NO.NEXTVAL, 1, 2, 'user02', 1234, '가의사', 'O', 'D', SYSDATE, '850504-1000000', 'b@alliswell.com', '01000000000', '0000000', '124-11-1541', 98000000);
INSERT INTO 
MEMBER
(NO, DEPARTMENT_NO, POSITION_NO, ID, PASSWORD, NAME, STATUS, POSITION_TYPE, ENROLL_DATE, REGISTRATION_NUMBER, EMAIL,  PHONE_NUMBER, OFFICE_NUMBER, LICENSE_NUMBER, YEAR_SALARY)
VALUES
(SEQ_MEMBER_NO.NEXTVAL, 1, 3, 'user03', 1234, '이의사', 'O', 'D', SYSDATE, '900105-1000000', 'c@alliswell.com', '01000000000', '0000000', '125-11-1241', 45000000);
INSERT INTO 
MEMBER
(NO, DEPARTMENT_NO, POSITION_NO, ID, PASSWORD, NAME, STATUS, POSITION_TYPE, ENROLL_DATE, REGISTRATION_NUMBER, EMAIL,  PHONE_NUMBER, OFFICE_NUMBER, LICENSE_NUMBER, YEAR_SALARY)
VALUES
(SEQ_MEMBER_NO.NEXTVAL, 1, 4, 'user04', 1234, '송의사', 'O', 'D', SYSDATE, '900105-1000000', 'dnslrpdla@naver.com', '01000000000', '0000000', '125-11-1241', 30000000);
INSERT INTO 
MEMBER
(NO, DEPARTMENT_NO, POSITION_NO, ID, PASSWORD, NAME, STATUS, POSITION_TYPE, ENROLL_DATE, REGISTRATION_NUMBER, EMAIL,  PHONE_NUMBER, OFFICE_NUMBER, LICENSE_NUMBER, YEAR_SALARY)
VALUES
(SEQ_MEMBER_NO.NEXTVAL, 1, 5, 'user05', 1234, '오간호', 'O', 'N', SYSDATE, '681105-2000000', 'f@alliswell.com', '01000000000', '0000000', '125-12-1811', 81000000);
INSERT INTO 
MEMBER
(NO, DEPARTMENT_NO, POSITION_NO, ID, PASSWORD, NAME, STATUS, POSITION_TYPE, ENROLL_DATE, REGISTRATION_NUMBER, EMAIL,  PHONE_NUMBER, OFFICE_NUMBER, LICENSE_NUMBER, YEAR_SALARY)
VALUES
(SEQ_MEMBER_NO.NEXTVAL, 1, 6, 'user06', 1234, '박간호', 'O', 'N', SYSDATE, '791111-2000000', 'g@alliswell.com', '01000000000', '0000000', '125-12-1811', 55000000);
INSERT INTO 
MEMBER
(NO, DEPARTMENT_NO, POSITION_NO, ID, PASSWORD, NAME, STATUS, POSITION_TYPE, ENROLL_DATE, REGISTRATION_NUMBER, EMAIL,  PHONE_NUMBER, OFFICE_NUMBER, LICENSE_NUMBER, YEAR_SALARY)
VALUES
(SEQ_MEMBER_NO.NEXTVAL, 1, 7, 'user07', 1234, '송간호', 'O', 'N', SYSDATE, '881111-2000000', 'i@alliswell.com', '01000000000', '0000000', '125-12-1811', 44000000);
INSERT INTO 
MEMBER
(NO, DEPARTMENT_NO, POSITION_NO, ID, PASSWORD, NAME, STATUS, POSITION_TYPE, ENROLL_DATE, REGISTRATION_NUMBER, EMAIL,  PHONE_NUMBER, OFFICE_NUMBER, LICENSE_NUMBER, YEAR_SALARY)
VALUES
(SEQ_MEMBER_NO.NEXTVAL, 1, 8, 'user08', 1234, '공간호', 'O', 'N', SYSDATE, '901111-2000000', 'j@alliswell.com', '01000000000', '0000000', '125-12-1811', 40000000);
INSERT INTO 
MEMBER
(NO, DEPARTMENT_NO, POSITION_NO, ID, PASSWORD, NAME, STATUS, POSITION_TYPE, ENROLL_DATE, REGISTRATION_NUMBER, EMAIL,  PHONE_NUMBER, OFFICE_NUMBER, LICENSE_NUMBER, YEAR_SALARY)
VALUES
(SEQ_MEMBER_NO.NEXTVAL, 1, 9, 'user09', 1234, '룩간호', 'O', 'N', SYSDATE, '951111-2000000', 'k@alliswell.com', '01000000000', '0000000', '125-12-1811', 35000000);

--2
INSERT INTO 
MEMBER
(NO, DEPARTMENT_NO, POSITION_NO, ID, PASSWORD, NAME, STATUS, POSITION_TYPE, ENROLL_DATE, REGISTRATION_NUMBER, EMAIL,  PHONE_NUMBER, OFFICE_NUMBER, LICENSE_NUMBER, YEAR_SALARY, PROFILE)
VALUES
(SEQ_MEMBER_NO.NEXTVAL, 2, 1, 'user11', 1234, '남궁의사', 'O', 'D', SYSDATE, '701012-1000000', 'aa@alliswell.com', '01000000000', '0000000', '123-98-1111', 108000000, '의사2.png');
INSERT INTO 
MEMBER
(NO, DEPARTMENT_NO, POSITION_NO, ID, PASSWORD, NAME, STATUS, POSITION_TYPE, ENROLL_DATE, REGISTRATION_NUMBER, EMAIL,  PHONE_NUMBER, OFFICE_NUMBER, LICENSE_NUMBER, YEAR_SALARY)
VALUES
(SEQ_MEMBER_NO.NEXTVAL, 2, 2, 'user12', 1234, '민의사', 'O', 'D', SYSDATE, '850504-1000000', 'bb@alliswell.com', '01000000000', '0000000', '124-11-1541', 98000000);
INSERT INTO 
MEMBER
(NO, DEPARTMENT_NO, POSITION_NO, ID, PASSWORD, NAME, STATUS, POSITION_TYPE, ENROLL_DATE, REGISTRATION_NUMBER, EMAIL,  PHONE_NUMBER, OFFICE_NUMBER, LICENSE_NUMBER, YEAR_SALARY)
VALUES
(SEQ_MEMBER_NO.NEXTVAL, 2, 3, 'user13', 1234, '홍의사', 'O', 'D', SYSDATE, '900105-1000000', 'cc@alliswell.com', '01000000000', '0000000', '125-11-1241', 45000000);
INSERT INTO 
MEMBER
(NO, DEPARTMENT_NO, POSITION_NO, ID, PASSWORD, NAME, STATUS, POSITION_TYPE, ENROLL_DATE, REGISTRATION_NUMBER, EMAIL,  PHONE_NUMBER, OFFICE_NUMBER, LICENSE_NUMBER, YEAR_SALARY)
VALUES
(SEQ_MEMBER_NO.NEXTVAL, 2, 4, 'user14', 1234, '의의사', 'O', 'D', SYSDATE, '900105-1000000', 'dd@alliswell.com', '01000000000', '0000000', '125-11-1241', 30000000);
INSERT INTO 
MEMBER
(NO, DEPARTMENT_NO, POSITION_NO, ID, PASSWORD, NAME, STATUS, POSITION_TYPE, ENROLL_DATE, REGISTRATION_NUMBER, EMAIL,  PHONE_NUMBER, OFFICE_NUMBER, LICENSE_NUMBER, YEAR_SALARY)
VALUES
(SEQ_MEMBER_NO.NEXTVAL, 2, 5, 'user15', 1234, '이간호', 'O', 'N', SYSDATE, '681105-2000000', 'ee@alliswell.com', '01000000000', '0000000', '125-12-1811', 99000000);
INSERT INTO 
MEMBER
(NO, DEPARTMENT_NO, POSITION_NO, ID, PASSWORD, NAME, STATUS, POSITION_TYPE, ENROLL_DATE, REGISTRATION_NUMBER, EMAIL,  PHONE_NUMBER, OFFICE_NUMBER, LICENSE_NUMBER, YEAR_SALARY)
VALUES
(SEQ_MEMBER_NO.NEXTVAL, 2, 6, 'user16', 1234, '영간호', 'O', 'N', SYSDATE, '791111-2000000', 'gg@alliswell.com', '01000000000', '0000000', '125-12-1811', 55000000);
INSERT INTO 
MEMBER
(NO, DEPARTMENT_NO, POSITION_NO, ID, PASSWORD, NAME, STATUS, POSITION_TYPE, ENROLL_DATE, REGISTRATION_NUMBER, EMAIL,  PHONE_NUMBER, OFFICE_NUMBER, LICENSE_NUMBER, YEAR_SALARY)
VALUES
(SEQ_MEMBER_NO.NEXTVAL, 2, 7, 'user17', 1234, '연간호', 'O', 'N', SYSDATE, '881111-2000000', 'ii@alliswell.com', '01000000000', '0000000', '125-12-1811', 44000000);
INSERT INTO 
MEMBER
(NO, DEPARTMENT_NO, POSITION_NO, ID, PASSWORD, NAME, STATUS, POSITION_TYPE, ENROLL_DATE, REGISTRATION_NUMBER, EMAIL,  PHONE_NUMBER, OFFICE_NUMBER, LICENSE_NUMBER, YEAR_SALARY)
VALUES
(SEQ_MEMBER_NO.NEXTVAL, 2, 8, 'user18', 1234, '감간호', 'O', 'N', SYSDATE, '901111-2000000', 'jj@alliswell.com', '01000000000', '0000000', '125-12-1811', 40000000);
INSERT INTO 
MEMBER
(NO, DEPARTMENT_NO, POSITION_NO, ID, PASSWORD, NAME, STATUS, POSITION_TYPE, ENROLL_DATE, REGISTRATION_NUMBER, EMAIL,  PHONE_NUMBER, OFFICE_NUMBER, LICENSE_NUMBER, YEAR_SALARY)
VALUES
(SEQ_MEMBER_NO.NEXTVAL, 2, 9, 'user19', 1234, '호간호', 'O', 'N', SYSDATE, '951111-2000000', 'kk@alliswell.com', '01000000000', '0000000', '125-12-1811', 35000000);


--3
INSERT INTO 
MEMBER
(NO, DEPARTMENT_NO, POSITION_NO, ID, PASSWORD, NAME, STATUS, POSITION_TYPE, ENROLL_DATE, REGISTRATION_NUMBER, EMAIL,  PHONE_NUMBER, OFFICE_NUMBER, LICENSE_NUMBER, YEAR_SALARY, PROFILE)
VALUES
(SEQ_MEMBER_NO.NEXTVAL, 3, 1, 'user21', 1234, '최의사', 'O', 'D', SYSDATE, '701012-1000000', 'aaa@alliswell.com', '01000000000', '0000000', '123-98-1111', 108000000, '의사3.png');
INSERT INTO 
MEMBER
(NO, DEPARTMENT_NO, POSITION_NO, ID, PASSWORD, NAME, STATUS, POSITION_TYPE, ENROLL_DATE, REGISTRATION_NUMBER, EMAIL,  PHONE_NUMBER, OFFICE_NUMBER, LICENSE_NUMBER, YEAR_SALARY)
VALUES
(SEQ_MEMBER_NO.NEXTVAL, 3, 2, 'user22', 1234, '남의사', 'O', 'D', SYSDATE, '850504-1000000', 'bbb@alliswell.com', '01000000000', '0000000', '124-11-1541', 98000000);
INSERT INTO 
MEMBER
(NO, DEPARTMENT_NO, POSITION_NO, ID, PASSWORD, NAME, STATUS, POSITION_TYPE, ENROLL_DATE, REGISTRATION_NUMBER, EMAIL,  PHONE_NUMBER, OFFICE_NUMBER, LICENSE_NUMBER, YEAR_SALARY)
VALUES
(SEQ_MEMBER_NO.NEXTVAL, 3, 3, 'user23', 1234, '여의사', 'O', 'D', SYSDATE, '900105-1000000', 'ccc@alliswell.com', '01000000000', '0000000', '125-11-1241', 45000000);
INSERT INTO 
MEMBER
(NO, DEPARTMENT_NO, POSITION_NO, ID, PASSWORD, NAME, STATUS, POSITION_TYPE, ENROLL_DATE, REGISTRATION_NUMBER, EMAIL,  PHONE_NUMBER, OFFICE_NUMBER, LICENSE_NUMBER, YEAR_SALARY)
VALUES
(SEQ_MEMBER_NO.NEXTVAL, 3, 4, 'user24', 1234, '중의사', 'O', 'D', SYSDATE, '900105-1000000', 'ddd@alliswell.com', '01000000000', '0000000', '125-11-1241', 30000000);
INSERT INTO 
MEMBER
(NO, DEPARTMENT_NO, POSITION_NO, ID, PASSWORD, NAME, STATUS, POSITION_TYPE, ENROLL_DATE, REGISTRATION_NUMBER, EMAIL,  PHONE_NUMBER, OFFICE_NUMBER, LICENSE_NUMBER, YEAR_SALARY)
VALUES
(SEQ_MEMBER_NO.NEXTVAL, 3, 5, 'user25', 1234, '경간호', 'O', 'N', SYSDATE, '681105-2000000', 'eee@alliswell.com', '01000000000', '0000000', '125-12-1811', 99000000);
INSERT INTO 
MEMBER
(NO, DEPARTMENT_NO, POSITION_NO, ID, PASSWORD, NAME, STATUS, POSITION_TYPE, ENROLL_DATE, REGISTRATION_NUMBER, EMAIL,  PHONE_NUMBER, OFFICE_NUMBER, LICENSE_NUMBER, YEAR_SALARY)
VALUES
(SEQ_MEMBER_NO.NEXTVAL, 3, 6, 'user26', 1234, '소간호', 'O', 'N', SYSDATE, '791111-2000000', 'ggg@alliswell.com', '01000000000', '0000000', '125-12-1811', 55000000);
INSERT INTO 
MEMBER
(NO, DEPARTMENT_NO, POSITION_NO, ID, PASSWORD, NAME, STATUS, POSITION_TYPE, ENROLL_DATE, REGISTRATION_NUMBER, EMAIL,  PHONE_NUMBER, OFFICE_NUMBER, LICENSE_NUMBER, YEAR_SALARY)
VALUES
(SEQ_MEMBER_NO.NEXTVAL, 3, 7, 'user27', 1234, '돈간호', 'O', 'N', SYSDATE, '881111-2000000', 'iii@alliswell.com', '01000000000', '0000000', '125-12-1811', 44000000);
INSERT INTO 
MEMBER
(NO, DEPARTMENT_NO, POSITION_NO, ID, PASSWORD, NAME, STATUS, POSITION_TYPE, ENROLL_DATE, REGISTRATION_NUMBER, EMAIL,  PHONE_NUMBER, OFFICE_NUMBER, LICENSE_NUMBER, YEAR_SALARY)
VALUES
(SEQ_MEMBER_NO.NEXTVAL, 3, 8, 'user28', 1234, '배간호', 'O', 'N', SYSDATE, '901111-2000000', 'jjj@alliswell.com', '01000000000', '0000000', '125-12-1811', 40000000);
INSERT INTO 
MEMBER
(NO, DEPARTMENT_NO, POSITION_NO, ID, PASSWORD, NAME, STATUS, POSITION_TYPE, ENROLL_DATE, REGISTRATION_NUMBER, EMAIL,  PHONE_NUMBER, OFFICE_NUMBER, LICENSE_NUMBER, YEAR_SALARY)
VALUES
(SEQ_MEMBER_NO.NEXTVAL, 3, 9, 'user29', 1234, '함간호', 'O', 'N', SYSDATE, '951111-2000000', 'kkk@alliswell.com', '01000000000', '0000000', '125-12-1811', 35000000);

--4
INSERT INTO 
MEMBER
(NO, DEPARTMENT_NO, POSITION_NO, ID, PASSWORD, NAME, STATUS, POSITION_TYPE, ENROLL_DATE, REGISTRATION_NUMBER, EMAIL,  PHONE_NUMBER, OFFICE_NUMBER, LICENSE_NUMBER, YEAR_SALARY, PROFILE)
VALUES
(SEQ_MEMBER_NO.NEXTVAL, 4, 1, 'user31', 1234, '황의사', 'O', 'D', SYSDATE, '701012-1000000', 'aaaa@alliswell.com', '01000000000', '0000000', '123-98-1111', 108000000, '의사4.png');
INSERT INTO 
MEMBER
(NO, DEPARTMENT_NO, POSITION_NO, ID, PASSWORD, NAME, STATUS, POSITION_TYPE, ENROLL_DATE, REGISTRATION_NUMBER, EMAIL,  PHONE_NUMBER, OFFICE_NUMBER, LICENSE_NUMBER, YEAR_SALARY)
VALUES
(SEQ_MEMBER_NO.NEXTVAL, 4, 2, 'user32', 1234, '가의사', 'O', 'D', SYSDATE, '850504-1000000', 'bbbb@alliswell.com', '01000000000', '0000000', '124-11-1541', 98000000);
INSERT INTO 
MEMBER
(NO, DEPARTMENT_NO, POSITION_NO, ID, PASSWORD, NAME, STATUS, POSITION_TYPE, ENROLL_DATE, REGISTRATION_NUMBER, EMAIL,  PHONE_NUMBER, OFFICE_NUMBER, LICENSE_NUMBER, YEAR_SALARY)
VALUES
(SEQ_MEMBER_NO.NEXTVAL, 4, 3, 'user33', 1234, '이의사', 'O', 'D', SYSDATE, '900105-1000000', 'cccc@alliswell.com', '01000000000', '0000000', '125-11-1241', 45000000);
INSERT INTO 
MEMBER
(NO, DEPARTMENT_NO, POSITION_NO, ID, PASSWORD, NAME, STATUS, POSITION_TYPE, ENROLL_DATE, REGISTRATION_NUMBER, EMAIL,  PHONE_NUMBER, OFFICE_NUMBER, LICENSE_NUMBER, YEAR_SALARY)
VALUES
(SEQ_MEMBER_NO.NEXTVAL, 4, 4, 'user34', 1234, '송의사', 'O', 'D', SYSDATE, '900105-1000000', 'dddd@alliswell.com', '01000000000', '0000000', '125-11-1241', 30000000);
INSERT INTO 
MEMBER
(NO, DEPARTMENT_NO, POSITION_NO, ID, PASSWORD, NAME, STATUS, POSITION_TYPE, ENROLL_DATE, REGISTRATION_NUMBER, EMAIL,  PHONE_NUMBER, OFFICE_NUMBER, LICENSE_NUMBER, YEAR_SALARY)
VALUES
(SEQ_MEMBER_NO.NEXTVAL, 4, 5, 'user35', 1234, '김간호', 'O', 'N', SYSDATE, '681105-2000000', 'eeee@alliswell.com', '01000000000', '0000000', '125-12-1811', 99000000);
INSERT INTO 
MEMBER
(NO, DEPARTMENT_NO, POSITION_NO, ID, PASSWORD, NAME, STATUS, POSITION_TYPE, ENROLL_DATE, REGISTRATION_NUMBER, EMAIL,  PHONE_NUMBER, OFFICE_NUMBER, LICENSE_NUMBER, YEAR_SALARY)
VALUES
(SEQ_MEMBER_NO.NEXTVAL, 4, 6, 'user36', 1234, '박간호', 'O', 'N', SYSDATE, '791111-2000000', 'gggg@alliswell.com', '01000000000', '0000000', '125-12-1811', 55000000);
INSERT INTO 
MEMBER
(NO, DEPARTMENT_NO, POSITION_NO, ID, PASSWORD, NAME, STATUS, POSITION_TYPE, ENROLL_DATE, REGISTRATION_NUMBER, EMAIL,  PHONE_NUMBER, OFFICE_NUMBER, LICENSE_NUMBER, YEAR_SALARY)
VALUES
(SEQ_MEMBER_NO.NEXTVAL, 4, 7, 'user37', 1234, '송간호', 'O', 'N', SYSDATE, '881111-2000000', 'iiii@alliswell.com', '01000000000', '0000000', '125-12-1811', 44000000);
INSERT INTO 
MEMBER
(NO, DEPARTMENT_NO, POSITION_NO, ID, PASSWORD, NAME, STATUS, POSITION_TYPE, ENROLL_DATE, REGISTRATION_NUMBER, EMAIL,  PHONE_NUMBER, OFFICE_NUMBER, LICENSE_NUMBER, YEAR_SALARY)
VALUES
(SEQ_MEMBER_NO.NEXTVAL, 4, 8, 'user38', 1234, '공간호', 'O', 'N', SYSDATE, '901111-2000000', 'jjjj@alliswell.com', '01000000000', '0000000', '125-12-1811', 40000000);
INSERT INTO 
MEMBER
(NO, DEPARTMENT_NO, POSITION_NO, ID, PASSWORD, NAME, STATUS, POSITION_TYPE, ENROLL_DATE, REGISTRATION_NUMBER, EMAIL,  PHONE_NUMBER, OFFICE_NUMBER, LICENSE_NUMBER, YEAR_SALARY)
VALUES
(SEQ_MEMBER_NO.NEXTVAL, 4, 9, 'user39', 1234, '룩간호', 'O', 'N', SYSDATE, '951111-2000000', 'kkkk@alliswell.com', '01000000000', '0000000', '125-12-1811', 35000000);


--5
INSERT INTO 
MEMBER
(NO, DEPARTMENT_NO, POSITION_NO, ID, PASSWORD, NAME, STATUS, POSITION_TYPE, ENROLL_DATE, REGISTRATION_NUMBER, EMAIL,  PHONE_NUMBER, OFFICE_NUMBER, LICENSE_NUMBER, YEAR_SALARY, PROFILE)
VALUES
(SEQ_MEMBER_NO.NEXTVAL, 5, 1, 'user41', 1234, '용의사', 'O', 'D', SYSDATE, '701012-1000000', 'aaaaa@alliswell.com', '01000000000', '0000000', '123-98-1111', 108000000, '의사5.png');
INSERT INTO 
MEMBER
(NO, DEPARTMENT_NO, POSITION_NO, ID, PASSWORD, NAME, STATUS, POSITION_TYPE, ENROLL_DATE, REGISTRATION_NUMBER, EMAIL,  PHONE_NUMBER, OFFICE_NUMBER, LICENSE_NUMBER, YEAR_SALARY)
VALUES
(SEQ_MEMBER_NO.NEXTVAL, 5, 2, 'user42', 1234, '가의사', 'O', 'D', SYSDATE, '850504-1000000', 'bbbbb@alliswell.com', '01000000000', '0000000', '124-11-1541', 98000000);
INSERT INTO 
MEMBER
(NO, DEPARTMENT_NO, POSITION_NO, ID, PASSWORD, NAME, STATUS, POSITION_TYPE, ENROLL_DATE, REGISTRATION_NUMBER, EMAIL,  PHONE_NUMBER, OFFICE_NUMBER, LICENSE_NUMBER, YEAR_SALARY)
VALUES
(SEQ_MEMBER_NO.NEXTVAL, 5, 3, 'user43', 1234, '이의사', 'O', 'D', SYSDATE, '900105-1000000', 'ccccc@alliswell.com', '01000000000', '0000000', '125-11-1241', 45000000);
INSERT INTO 
MEMBER
(NO, DEPARTMENT_NO, POSITION_NO, ID, PASSWORD, NAME, STATUS, POSITION_TYPE, ENROLL_DATE, REGISTRATION_NUMBER, EMAIL,  PHONE_NUMBER, OFFICE_NUMBER, LICENSE_NUMBER, YEAR_SALARY)
VALUES
(SEQ_MEMBER_NO.NEXTVAL, 5, 4, 'user44', 1234, '송의사', 'O', 'D', SYSDATE, '900105-1000000', 'ddddd@alliswell.com', '01000000000', '0000000', '125-11-1241', 30000000);
INSERT INTO 
MEMBER
(NO, DEPARTMENT_NO, POSITION_NO, ID, PASSWORD, NAME, STATUS, POSITION_TYPE, ENROLL_DATE, REGISTRATION_NUMBER, EMAIL,  PHONE_NUMBER, OFFICE_NUMBER, LICENSE_NUMBER, YEAR_SALARY)
VALUES
(SEQ_MEMBER_NO.NEXTVAL, 5, 5, 'user45', 1234, '김간호', 'O', 'N', SYSDATE, '681105-2000000', 'eeeee@alliswell.com', '01000000000', '0000000', '125-12-1811', 99000000);
INSERT INTO 
MEMBER
(NO, DEPARTMENT_NO, POSITION_NO, ID, PASSWORD, NAME, STATUS, POSITION_TYPE, ENROLL_DATE, REGISTRATION_NUMBER, EMAIL,  PHONE_NUMBER, OFFICE_NUMBER, LICENSE_NUMBER, YEAR_SALARY)
VALUES
(SEQ_MEMBER_NO.NEXTVAL, 5, 6, 'user46', 1234, '박간호', 'O', 'N', SYSDATE, '791111-2000000', 'ggggg@alliswell.com', '01000000000', '0000000', '125-12-1811', 55000000);
INSERT INTO 
MEMBER
(NO, DEPARTMENT_NO, POSITION_NO, ID, PASSWORD, NAME, STATUS, POSITION_TYPE, ENROLL_DATE, REGISTRATION_NUMBER, EMAIL,  PHONE_NUMBER, OFFICE_NUMBER, LICENSE_NUMBER, YEAR_SALARY)
VALUES
(SEQ_MEMBER_NO.NEXTVAL, 5, 7, 'user47', 1234, '송간호', 'O', 'N', SYSDATE, '881111-2000000', 'iiiii@alliswell.com', '01000000000', '0000000', '125-12-1811', 44000000);
INSERT INTO 
MEMBER
(NO, DEPARTMENT_NO, POSITION_NO, ID, PASSWORD, NAME, STATUS, POSITION_TYPE, ENROLL_DATE, REGISTRATION_NUMBER, EMAIL,  PHONE_NUMBER, OFFICE_NUMBER, LICENSE_NUMBER, YEAR_SALARY)
VALUES
(SEQ_MEMBER_NO.NEXTVAL, 5, 8, 'user48', 1234, '공간호', 'O', 'N', SYSDATE, '901111-2000000', 'jjjjj@alliswell.com', '01000000000', '0000000', '125-12-1811', 40000000);
INSERT INTO 
MEMBER
(NO, DEPARTMENT_NO, POSITION_NO, ID, PASSWORD, NAME, STATUS, POSITION_TYPE, ENROLL_DATE, REGISTRATION_NUMBER, EMAIL,  PHONE_NUMBER, OFFICE_NUMBER, LICENSE_NUMBER, YEAR_SALARY)
VALUES
(SEQ_MEMBER_NO.NEXTVAL, 5, 9, 'user49', 1234, '룩간호', 'O', 'N', SYSDATE, '951111-2000000', 'kkkkk@alliswell.com', '01000000000', '0000000', '125-12-1811', 35000000);


--6
INSERT INTO 
MEMBER
(NO, DEPARTMENT_NO, POSITION_NO, ID, PASSWORD, NAME, STATUS, POSITION_TYPE, ENROLL_DATE, REGISTRATION_NUMBER, EMAIL,  PHONE_NUMBER, OFFICE_NUMBER, LICENSE_NUMBER, YEAR_SALARY, PROFILE)
VALUES
(SEQ_MEMBER_NO.NEXTVAL, 6, 1, 'user51', 1234, '호의사', 'O', 'D', SYSDATE, '701012-1000000', 'aaaaaa@alliswell.com', '01000000000', '0000000', '123-98-1111', 108000000, '의사6.png');
INSERT INTO 
MEMBER
(NO, DEPARTMENT_NO, POSITION_NO, ID, PASSWORD, NAME, STATUS, POSITION_TYPE, ENROLL_DATE, REGISTRATION_NUMBER, EMAIL,  PHONE_NUMBER, OFFICE_NUMBER, LICENSE_NUMBER, YEAR_SALARY)
VALUES
(SEQ_MEMBER_NO.NEXTVAL, 6, 2, 'user52', 1234, '가의사', 'O', 'D', SYSDATE, '850504-1000000', 'bbbbbb@alliswell.com', '01000000000', '0000000', '124-11-1541', 98000000);
INSERT INTO 
MEMBER
(NO, DEPARTMENT_NO, POSITION_NO, ID, PASSWORD, NAME, STATUS, POSITION_TYPE, ENROLL_DATE, REGISTRATION_NUMBER, EMAIL,  PHONE_NUMBER, OFFICE_NUMBER, LICENSE_NUMBER, YEAR_SALARY)
VALUES
(SEQ_MEMBER_NO.NEXTVAL, 6, 3, 'user53', 1234, '이의사', 'O', 'D', SYSDATE, '900105-1000000', 'cccccc@alliswell.com', '01000000000', '0000000', '125-11-1241', 45000000);
INSERT INTO 
MEMBER
(NO, DEPARTMENT_NO, POSITION_NO, ID, PASSWORD, NAME, STATUS, POSITION_TYPE, ENROLL_DATE, REGISTRATION_NUMBER, EMAIL,  PHONE_NUMBER, OFFICE_NUMBER, LICENSE_NUMBER, YEAR_SALARY)
VALUES
(SEQ_MEMBER_NO.NEXTVAL, 6, 4, 'user54', 1234, '송의사', 'O', 'D', SYSDATE, '900105-1000000', 'dddddd@alliswell.com', '01000000000', '0000000', '125-11-1241', 30000000);
INSERT INTO 
MEMBER
(NO, DEPARTMENT_NO, POSITION_NO, ID, PASSWORD, NAME, STATUS, POSITION_TYPE, ENROLL_DATE, REGISTRATION_NUMBER, EMAIL,  PHONE_NUMBER, OFFICE_NUMBER, LICENSE_NUMBER, YEAR_SALARY)
VALUES
(SEQ_MEMBER_NO.NEXTVAL, 6, 5, 'user55', 1234, '김간호', 'O', 'N', SYSDATE, '681105-2000000', 'eeeeee@alliswell.com', '01000000000', '0000000', '125-12-1811', 99000000);
INSERT INTO 
MEMBER
(NO, DEPARTMENT_NO, POSITION_NO, ID, PASSWORD, NAME, STATUS, POSITION_TYPE, ENROLL_DATE, REGISTRATION_NUMBER, EMAIL,  PHONE_NUMBER, OFFICE_NUMBER, LICENSE_NUMBER, YEAR_SALARY)
VALUES
(SEQ_MEMBER_NO.NEXTVAL, 6, 6, 'user56', 1234, '박간호', 'O', 'N', SYSDATE, '791111-2000000', 'gggggg@alliswell.com', '01000000000', '0000000', '125-12-1811', 55000000);
INSERT INTO 
MEMBER
(NO, DEPARTMENT_NO, POSITION_NO, ID, PASSWORD, NAME, STATUS, POSITION_TYPE, ENROLL_DATE, REGISTRATION_NUMBER, EMAIL,  PHONE_NUMBER, OFFICE_NUMBER, LICENSE_NUMBER, YEAR_SALARY)
VALUES
(SEQ_MEMBER_NO.NEXTVAL, 6, 7, 'user57', 1234, '송간호', 'O', 'N', SYSDATE, '881111-2000000', 'iiiiii@alliswell.com', '01000000000', '0000000', '125-12-1811', 44000000);
INSERT INTO 
MEMBER
(NO, DEPARTMENT_NO, POSITION_NO, ID, PASSWORD, NAME, STATUS, POSITION_TYPE, ENROLL_DATE, REGISTRATION_NUMBER, EMAIL,  PHONE_NUMBER, OFFICE_NUMBER, LICENSE_NUMBER, YEAR_SALARY)
VALUES
(SEQ_MEMBER_NO.NEXTVAL, 6, 8, 'user58', 1234, '공간호', 'O', 'N', SYSDATE, '901111-2000000', 'jjjjjj@alliswell.com', '01000000000', '0000000', '125-12-1811', 40000000);
INSERT INTO 
MEMBER
(NO, DEPARTMENT_NO, POSITION_NO, ID, PASSWORD, NAME, STATUS, POSITION_TYPE, ENROLL_DATE, REGISTRATION_NUMBER, EMAIL,  PHONE_NUMBER, OFFICE_NUMBER, LICENSE_NUMBER, YEAR_SALARY)
VALUES
(SEQ_MEMBER_NO.NEXTVAL, 6, 9, 'user59', 1234, '룩간호', 'O', 'N', SYSDATE, '951111-2000000', 'kkkkkk@alliswell.com', '01000000000', '0000000', '125-12-1811', 35000000);

--7
INSERT INTO 
MEMBER
(NO, DEPARTMENT_NO, POSITION_NO, ID, PASSWORD, NAME, STATUS, POSITION_TYPE, ENROLL_DATE, REGISTRATION_NUMBER, EMAIL,  PHONE_NUMBER, OFFICE_NUMBER, LICENSE_NUMBER, YEAR_SALARY, PROFILE)
VALUES
(SEQ_MEMBER_NO.NEXTVAL, 7, 1, 'user61', 1234, '현의사', 'O', 'D', SYSDATE, '701012-1000000', 'aaaaaaa@alliswell.com', '01000000000', '0000000', '123-98-1111', 108000000, '의사7.png');
INSERT INTO 
MEMBER
(NO, DEPARTMENT_NO, POSITION_NO, ID, PASSWORD, NAME, STATUS, POSITION_TYPE, ENROLL_DATE, REGISTRATION_NUMBER, EMAIL,  PHONE_NUMBER, OFFICE_NUMBER, LICENSE_NUMBER, YEAR_SALARY)
VALUES
(SEQ_MEMBER_NO.NEXTVAL, 7, 2, 'user62', 1234, '가의사', 'O', 'D', SYSDATE, '850504-1000000', 'bbbbbbb@alliswell.com', '01000000000', '0000000', '124-11-1541', 98000000);
INSERT INTO 
MEMBER
(NO, DEPARTMENT_NO, POSITION_NO, ID, PASSWORD, NAME, STATUS, POSITION_TYPE, ENROLL_DATE, REGISTRATION_NUMBER, EMAIL,  PHONE_NUMBER, OFFICE_NUMBER, LICENSE_NUMBER, YEAR_SALARY)
VALUES
(SEQ_MEMBER_NO.NEXTVAL, 7, 3, 'user63', 1234, '이의사', 'O', 'D', SYSDATE, '900105-1000000', 'ccccccc@alliswell.com', '01000000000', '0000000', '125-11-1241', 45000000);
INSERT INTO 
MEMBER
(NO, DEPARTMENT_NO, POSITION_NO, ID, PASSWORD, NAME, STATUS, POSITION_TYPE, ENROLL_DATE, REGISTRATION_NUMBER, EMAIL,  PHONE_NUMBER, OFFICE_NUMBER, LICENSE_NUMBER, YEAR_SALARY)
VALUES
(SEQ_MEMBER_NO.NEXTVAL, 7, 4, 'user64', 1234, '송의사', 'O', 'D', SYSDATE, '900105-1000000', 'ddddddd@alliswell.com', '01000000000', '0000000', '125-11-1241', 30000000);
INSERT INTO 
MEMBER
(NO, DEPARTMENT_NO, POSITION_NO, ID, PASSWORD, NAME, STATUS, POSITION_TYPE, ENROLL_DATE, REGISTRATION_NUMBER, EMAIL,  PHONE_NUMBER, OFFICE_NUMBER, LICENSE_NUMBER, YEAR_SALARY)
VALUES
(SEQ_MEMBER_NO.NEXTVAL, 7, 5, 'user65', 1234, '김간호', 'O', 'N', SYSDATE, '681105-2000000', 'eeeeeee@alliswell.com', '01000000000', '0000000', '125-12-1811', 99000000);
INSERT INTO 
MEMBER
(NO, DEPARTMENT_NO, POSITION_NO, ID, PASSWORD, NAME, STATUS, POSITION_TYPE, ENROLL_DATE, REGISTRATION_NUMBER, EMAIL,  PHONE_NUMBER, OFFICE_NUMBER, LICENSE_NUMBER, YEAR_SALARY)
VALUES
(SEQ_MEMBER_NO.NEXTVAL, 7, 6, 'user66', 1234, '박간호', 'O', 'N', SYSDATE, '791111-2000000', 'ggggggg@alliswell.com', '01000000000', '0000000', '125-12-1811', 55000000);
INSERT INTO 
MEMBER
(NO, DEPARTMENT_NO, POSITION_NO, ID, PASSWORD, NAME, STATUS, POSITION_TYPE, ENROLL_DATE, REGISTRATION_NUMBER, EMAIL,  PHONE_NUMBER, OFFICE_NUMBER, LICENSE_NUMBER, YEAR_SALARY)
VALUES
(SEQ_MEMBER_NO.NEXTVAL, 7, 7, 'user67', 1234, '송간호', 'O', 'N', SYSDATE, '881111-2000000', 'iiiiiii@alliswell.com', '01000000000', '0000000', '125-12-1811', 44000000);
INSERT INTO 
MEMBER
(NO, DEPARTMENT_NO, POSITION_NO, ID, PASSWORD, NAME, STATUS, POSITION_TYPE, ENROLL_DATE, REGISTRATION_NUMBER, EMAIL,  PHONE_NUMBER, OFFICE_NUMBER, LICENSE_NUMBER, YEAR_SALARY)
VALUES
(SEQ_MEMBER_NO.NEXTVAL, 7, 8, 'user68', 1234, '공간호', 'O', 'N', SYSDATE, '901111-2000000', 'jjjjjjj@alliswell.com', '01000000000', '0000000', '125-12-1811', 40000000);
INSERT INTO 
MEMBER
(NO, DEPARTMENT_NO, POSITION_NO, ID, PASSWORD, NAME, STATUS, POSITION_TYPE, ENROLL_DATE, REGISTRATION_NUMBER, EMAIL,  PHONE_NUMBER, OFFICE_NUMBER, LICENSE_NUMBER, YEAR_SALARY)
VALUES
(SEQ_MEMBER_NO.NEXTVAL, 7, 9, 'user69', 1234, '룩간호', 'O', 'N', SYSDATE, '951111-2000000', 'kkkkkkk@alliswell.com', '01000000000', '0000000', '125-12-1811', 35000000);


--8
INSERT INTO 
MEMBER
(NO, DEPARTMENT_NO, POSITION_NO, ID, PASSWORD, NAME, STATUS, POSITION_TYPE, ENROLL_DATE, REGISTRATION_NUMBER, EMAIL,  PHONE_NUMBER, OFFICE_NUMBER, LICENSE_NUMBER, YEAR_SALARY, PROFILE)
VALUES
(SEQ_MEMBER_NO.NEXTVAL, 8, 1, 'user71', 1234, '조의사', 'O', 'D', SYSDATE, '701012-1000000', 'aaaaaaaa@alliswell.com', '01000000000', '0000000', '123-98-1111', 108000000, '의사8.png');
INSERT INTO 
MEMBER
(NO, DEPARTMENT_NO, POSITION_NO, ID, PASSWORD, NAME, STATUS, POSITION_TYPE, ENROLL_DATE, REGISTRATION_NUMBER, EMAIL,  PHONE_NUMBER, OFFICE_NUMBER, LICENSE_NUMBER, YEAR_SALARY)
VALUES
(SEQ_MEMBER_NO.NEXTVAL, 8, 2, 'user72', 1234, '가의사', 'O', 'D', SYSDATE, '850504-1000000', 'bbbbbbbb@alliswell.com', '01000000000', '0000000', '124-11-1541', 98000000);
INSERT INTO 
MEMBER
(NO, DEPARTMENT_NO, POSITION_NO, ID, PASSWORD, NAME, STATUS, POSITION_TYPE, ENROLL_DATE, REGISTRATION_NUMBER, EMAIL,  PHONE_NUMBER, OFFICE_NUMBER, LICENSE_NUMBER, YEAR_SALARY)
VALUES
(SEQ_MEMBER_NO.NEXTVAL, 8, 3, 'user73', 1234, '이의사', 'O', 'D', SYSDATE, '900105-1000000', 'cccccccc@alliswell.com', '01000000000', '0000000', '125-11-1241', 45000000);
INSERT INTO 
MEMBER
(NO, DEPARTMENT_NO, POSITION_NO, ID, PASSWORD, NAME, STATUS, POSITION_TYPE, ENROLL_DATE, REGISTRATION_NUMBER, EMAIL,  PHONE_NUMBER, OFFICE_NUMBER, LICENSE_NUMBER, YEAR_SALARY)
VALUES
(SEQ_MEMBER_NO.NEXTVAL, 8, 4, 'user74', 1234, '송의사', 'O', 'D', SYSDATE, '900105-1000000', 'dddddddd@alliswell.com', '01000000000', '0000000', '125-11-1241', 30000000);
INSERT INTO 
MEMBER
(NO, DEPARTMENT_NO, POSITION_NO, ID, PASSWORD, NAME, STATUS, POSITION_TYPE, ENROLL_DATE, REGISTRATION_NUMBER, EMAIL,  PHONE_NUMBER, OFFICE_NUMBER, LICENSE_NUMBER, YEAR_SALARY)
VALUES
(SEQ_MEMBER_NO.NEXTVAL, 8, 5, 'user75', 1234, '김간호', 'O', 'N', SYSDATE, '681105-2000000', 'eeeeeeee@alliswell.com', '01000000000', '0000000', '125-12-1811', 99000000);
INSERT INTO 
MEMBER
(NO, DEPARTMENT_NO, POSITION_NO, ID, PASSWORD, NAME, STATUS, POSITION_TYPE, ENROLL_DATE, REGISTRATION_NUMBER, EMAIL,  PHONE_NUMBER, OFFICE_NUMBER, LICENSE_NUMBER, YEAR_SALARY)
VALUES
(SEQ_MEMBER_NO.NEXTVAL, 8, 6, 'user76', 1234, '박간호', 'O', 'N', SYSDATE, '791111-2000000', 'gggggggg@alliswell.com', '01000000000', '0000000', '125-12-1811', 55000000);
INSERT INTO 
MEMBER
(NO, DEPARTMENT_NO, POSITION_NO, ID, PASSWORD, NAME, STATUS, POSITION_TYPE, ENROLL_DATE, REGISTRATION_NUMBER, EMAIL,  PHONE_NUMBER, OFFICE_NUMBER, LICENSE_NUMBER, YEAR_SALARY)
VALUES
(SEQ_MEMBER_NO.NEXTVAL, 8, 7, 'user77', 1234, '송간호', 'O', 'N', SYSDATE, '881111-2000000', 'iiiiiiii@alliswell.com', '01000000000', '0000000', '125-12-1811', 44000000);
INSERT INTO 
MEMBER
(NO, DEPARTMENT_NO, POSITION_NO, ID, PASSWORD, NAME, STATUS, POSITION_TYPE, ENROLL_DATE, REGISTRATION_NUMBER, EMAIL,  PHONE_NUMBER, OFFICE_NUMBER, LICENSE_NUMBER, YEAR_SALARY)
VALUES
(SEQ_MEMBER_NO.NEXTVAL, 8, 8, 'user78', 1234, '공간호', 'O', 'N', SYSDATE, '901111-2000000', 'jjjjjjjj@alliswell.com', '01000000000', '0000000', '125-12-1811', 40000000);
INSERT INTO 
MEMBER
(NO, DEPARTMENT_NO, POSITION_NO, ID, PASSWORD, NAME, STATUS, POSITION_TYPE, ENROLL_DATE, REGISTRATION_NUMBER, EMAIL,  PHONE_NUMBER, OFFICE_NUMBER, LICENSE_NUMBER, YEAR_SALARY)
VALUES
(SEQ_MEMBER_NO.NEXTVAL, 8, 9, 'user79', 1234, '룩간호', 'O', 'N', SYSDATE, '951111-2000000', 'kkkkkkkk@alliswell.com', '01000000000', '0000000', '125-12-1811', 35000000);

--9
INSERT INTO 
MEMBER
(NO, DEPARTMENT_NO, POSITION_NO, ID, PASSWORD, NAME, STATUS, POSITION_TYPE, ENROLL_DATE, REGISTRATION_NUMBER, EMAIL,  PHONE_NUMBER, OFFICE_NUMBER, LICENSE_NUMBER, YEAR_SALARY, PROFILE)
VALUES
(SEQ_MEMBER_NO.NEXTVAL, 9, 1, 'user81', 1234, '남이사', 'O', 'D', SYSDATE, '701012-1000000', 'aaaaaaaaa@alliswell.com', '01000000000', '0000000', '123-98-1111', 108000000, '의사9.png');
INSERT INTO 
MEMBER
(NO, DEPARTMENT_NO, POSITION_NO, ID, PASSWORD, NAME, STATUS, POSITION_TYPE, ENROLL_DATE, REGISTRATION_NUMBER, EMAIL,  PHONE_NUMBER, OFFICE_NUMBER, LICENSE_NUMBER, YEAR_SALARY)
VALUES
(SEQ_MEMBER_NO.NEXTVAL, 9, 2, 'user82', 1234, '가의사', 'O', 'D', SYSDATE, '850504-1000000', 'bbbbbbbbb@alliswell.com', '01000000000', '0000000', '124-11-1541', 98000000);
INSERT INTO 
MEMBER
(NO, DEPARTMENT_NO, POSITION_NO, ID, PASSWORD, NAME, STATUS, POSITION_TYPE, ENROLL_DATE, REGISTRATION_NUMBER, EMAIL,  PHONE_NUMBER, OFFICE_NUMBER, LICENSE_NUMBER, YEAR_SALARY)
VALUES
(SEQ_MEMBER_NO.NEXTVAL, 9, 3, 'user83', 1234, '이의사', 'O', 'D', SYSDATE, '900105-1000000', 'ccccccccc@alliswell.com', '01000000000', '0000000', '125-11-1241', 45000000);
INSERT INTO 
MEMBER
(NO, DEPARTMENT_NO, POSITION_NO, ID, PASSWORD, NAME, STATUS, POSITION_TYPE, ENROLL_DATE, REGISTRATION_NUMBER, EMAIL,  PHONE_NUMBER, OFFICE_NUMBER, LICENSE_NUMBER, YEAR_SALARY)
VALUES
(SEQ_MEMBER_NO.NEXTVAL, 9, 4, 'user84', 1234, '송의사', 'O', 'D', SYSDATE, '900105-1000000', 'ddddddddd@alliswell.com', '01000000000', '0000000', '125-11-1241', 30000000);
INSERT INTO 
MEMBER
(NO, DEPARTMENT_NO, POSITION_NO, ID, PASSWORD, NAME, STATUS, POSITION_TYPE, ENROLL_DATE, REGISTRATION_NUMBER, EMAIL,  PHONE_NUMBER, OFFICE_NUMBER, LICENSE_NUMBER, YEAR_SALARY)
VALUES
(SEQ_MEMBER_NO.NEXTVAL, 9, 5, 'user85', 1234, '김간호', 'O', 'N', SYSDATE, '681105-2000000', 'eeeeeeeee@alliswell.com', '01000000000', '0000000', '125-12-1811', 99000000);
INSERT INTO 
MEMBER
(NO, DEPARTMENT_NO, POSITION_NO, ID, PASSWORD, NAME, STATUS, POSITION_TYPE, ENROLL_DATE, REGISTRATION_NUMBER, EMAIL,  PHONE_NUMBER, OFFICE_NUMBER, LICENSE_NUMBER, YEAR_SALARY)
VALUES
(SEQ_MEMBER_NO.NEXTVAL, 9, 6, 'user86', 1234, '박간호', 'O', 'N', SYSDATE, '791111-2000000', 'ggggggggg@alliswell.com', '01000000000', '0000000', '125-12-1811', 55000000);
INSERT INTO 
MEMBER
(NO, DEPARTMENT_NO, POSITION_NO, ID, PASSWORD, NAME, STATUS, POSITION_TYPE, ENROLL_DATE, REGISTRATION_NUMBER, EMAIL,  PHONE_NUMBER, OFFICE_NUMBER, LICENSE_NUMBER, YEAR_SALARY)
VALUES
(SEQ_MEMBER_NO.NEXTVAL, 9, 7, 'user87', 1234, '송간호', 'O', 'N', SYSDATE, '881111-2000000', 'iiiiiiiii@alliswell.com', '01000000000', '0000000', '125-12-1811', 44000000);
INSERT INTO 
MEMBER
(NO, DEPARTMENT_NO, POSITION_NO, ID, PASSWORD, NAME, STATUS, POSITION_TYPE, ENROLL_DATE, REGISTRATION_NUMBER, EMAIL,  PHONE_NUMBER, OFFICE_NUMBER, LICENSE_NUMBER, YEAR_SALARY)
VALUES
(SEQ_MEMBER_NO.NEXTVAL, 9, 8, 'user88', 1234, '공간호', 'O', 'N', SYSDATE, '901111-2000000', 'jjjjjjjjj@alliswell.com', '01000000000', '0000000', '125-12-1811', 40000000);
INSERT INTO 
MEMBER
(NO, DEPARTMENT_NO, POSITION_NO, ID, PASSWORD, NAME, STATUS, POSITION_TYPE, ENROLL_DATE, REGISTRATION_NUMBER, EMAIL,  PHONE_NUMBER, OFFICE_NUMBER, LICENSE_NUMBER, YEAR_SALARY)
VALUES
(SEQ_MEMBER_NO.NEXTVAL, 9, 9, 'user89', 1234, '룩간호', 'O', 'N', SYSDATE, '951111-2000000', 'kkkkkkkkk@alliswell.com', '01000000000', '0000000', '125-12-1811', 35000000);

--10
INSERT INTO 
MEMBER
(NO, DEPARTMENT_NO, POSITION_NO, ID, PASSWORD, NAME, STATUS, POSITION_TYPE, ENROLL_DATE, REGISTRATION_NUMBER, EMAIL,  PHONE_NUMBER, OFFICE_NUMBER, LICENSE_NUMBER, YEAR_SALARY)
VALUES
(SEQ_MEMBER_NO.NEXTVAL, 10, 1, 'user91', 1234, '김의사', 'O', 'D', SYSDATE, '701012-1000000', 'aaaaaaaaaa@alliswell.com', '01000000000', '0000000', '123-98-1111', 108000000);
INSERT INTO 
MEMBER
(NO, DEPARTMENT_NO, POSITION_NO, ID, PASSWORD, NAME, STATUS, POSITION_TYPE, ENROLL_DATE, REGISTRATION_NUMBER, EMAIL,  PHONE_NUMBER, OFFICE_NUMBER, LICENSE_NUMBER, YEAR_SALARY)
VALUES
(SEQ_MEMBER_NO.NEXTVAL, 10, 2, 'user92', 1234, '가의사', 'O', 'D', SYSDATE, '850504-1000000', 'bbbbbbbbbb@alliswell.com', '01000000000', '0000000', '124-11-1541', 98000000);
INSERT INTO 
MEMBER
(NO, DEPARTMENT_NO, POSITION_NO, ID, PASSWORD, NAME, STATUS, POSITION_TYPE, ENROLL_DATE, REGISTRATION_NUMBER, EMAIL,  PHONE_NUMBER, OFFICE_NUMBER, LICENSE_NUMBER, YEAR_SALARY)
VALUES
(SEQ_MEMBER_NO.NEXTVAL, 10, 3, 'user93', 1234, '이의사', 'O', 'D', SYSDATE, '900105-1000000', 'cccccccccc@alliswell.com', '01000000000', '0000000', '125-11-1241', 45000000);
INSERT INTO 
MEMBER
(NO, DEPARTMENT_NO, POSITION_NO, ID, PASSWORD, NAME, STATUS, POSITION_TYPE, ENROLL_DATE, REGISTRATION_NUMBER, EMAIL,  PHONE_NUMBER, OFFICE_NUMBER, LICENSE_NUMBER, YEAR_SALARY)
VALUES
(SEQ_MEMBER_NO.NEXTVAL, 10, 4, 'user94', 1234, '송의사', 'O', 'D', SYSDATE, '900105-1000000', 'dddddddddd@alliswell.com', '01000000000', '0000000', '125-11-1241', 30000000);
INSERT INTO 
MEMBER
(NO, DEPARTMENT_NO, POSITION_NO, ID, PASSWORD, NAME, STATUS, POSITION_TYPE, ENROLL_DATE, REGISTRATION_NUMBER, EMAIL,  PHONE_NUMBER, OFFICE_NUMBER, LICENSE_NUMBER, YEAR_SALARY)
VALUES
(SEQ_MEMBER_NO.NEXTVAL, 10, 5, 'user95', 1234, '김간호', 'O', 'N', SYSDATE, '681105-2000000', 'eeeeeeeeee@alliswell.com', '01000000000', '0000000', '125-12-1811', 99000000);
INSERT INTO 
MEMBER
(NO, DEPARTMENT_NO, POSITION_NO, ID, PASSWORD, NAME, STATUS, POSITION_TYPE, ENROLL_DATE, REGISTRATION_NUMBER, EMAIL,  PHONE_NUMBER, OFFICE_NUMBER, LICENSE_NUMBER, YEAR_SALARY)
VALUES
(SEQ_MEMBER_NO.NEXTVAL, 10, 6, 'user96', 1234, '박간호', 'O', 'N', SYSDATE, '791111-2000000', 'gggggggggg@alliswell.com', '01000000000', '0000000', '125-12-1811', 55000000);
INSERT INTO 
MEMBER
(NO, DEPARTMENT_NO, POSITION_NO, ID, PASSWORD, NAME, STATUS, POSITION_TYPE, ENROLL_DATE, REGISTRATION_NUMBER, EMAIL,  PHONE_NUMBER, OFFICE_NUMBER, LICENSE_NUMBER, YEAR_SALARY)
VALUES
(SEQ_MEMBER_NO.NEXTVAL, 10, 7, 'user97', 1234, '송간호', 'O', 'N', SYSDATE, '881111-2000000', 'iiiiiiiiii@alliswell.com', '01000000000', '0000000', '125-12-1811', 44000000);
INSERT INTO 
MEMBER
(NO, DEPARTMENT_NO, POSITION_NO, ID, PASSWORD, NAME, STATUS, POSITION_TYPE, ENROLL_DATE, REGISTRATION_NUMBER, EMAIL,  PHONE_NUMBER, OFFICE_NUMBER, LICENSE_NUMBER, YEAR_SALARY)
VALUES
(SEQ_MEMBER_NO.NEXTVAL, 10, 8, 'user98', 1234, '공간호', 'O', 'N', SYSDATE, '901111-2000000', 'jjjjjjjjjj@alliswell.com', '01000000000', '0000000', '125-12-1811', 40000000);
INSERT INTO 
MEMBER
(NO, DEPARTMENT_NO, POSITION_NO, ID, PASSWORD, NAME, STATUS, POSITION_TYPE, ENROLL_DATE, REGISTRATION_NUMBER, EMAIL,  PHONE_NUMBER, OFFICE_NUMBER, LICENSE_NUMBER, YEAR_SALARY)
VALUES
(SEQ_MEMBER_NO.NEXTVAL, 10, 9, 'user99', 1234, '룩간호', 'O', 'N', SYSDATE, '951111-2000000', 'kkkkkkkkkk@alliswell.com', '01000000000', '0000000', '125-12-1811', 35000000);

--ATTENDANCE
INSERT INTO ATTENDANCE(NO, MEMBER_NO, PRESENCE_TIME, LEAVE_TIME) VALUES(SEQ_ATTENDANCE_NO.NEXTVAL, 1, TO_TIMESTAMP('2023-07-31 08:30:55'), TO_TIMESTAMP('2023-07-31 23:14:12'));
INSERT INTO ATTENDANCE(NO, MEMBER_NO, PRESENCE_TIME, LEAVE_TIME) VALUES(SEQ_ATTENDANCE_NO.NEXTVAL, 1, TO_TIMESTAMP('2023-08-01 09:00:05'), TO_TIMESTAMP('2023-08-01 18:10:17'));
INSERT INTO ATTENDANCE(NO, MEMBER_NO, PRESENCE_TIME, LEAVE_TIME) VALUES(SEQ_ATTENDANCE_NO.NEXTVAL, 1, TO_TIMESTAMP('2023-08-02 08:59:33'), TO_TIMESTAMP('2023-08-02 18:15:22'));
INSERT INTO ATTENDANCE(NO, MEMBER_NO, PRESENCE_TIME, LEAVE_TIME) VALUES(SEQ_ATTENDANCE_NO.NEXTVAL, 1, TO_TIMESTAMP('2023-08-03 09:03:22'), TO_TIMESTAMP('2023-08-03 18:25:39'));
INSERT INTO ATTENDANCE(NO, MEMBER_NO, PRESENCE_TIME, LEAVE_TIME) VALUES(SEQ_ATTENDANCE_NO.NEXTVAL, 1, TO_TIMESTAMP('2023-08-04 08:33:49'), TO_TIMESTAMP('2023-08-04 19:22:56'));
INSERT INTO ATTENDANCE(NO, MEMBER_NO, PRESENCE_TIME, LEAVE_TIME) VALUES(SEQ_ATTENDANCE_NO.NEXTVAL, 1, TO_TIMESTAMP('2023-08-07 08:48:11'), TO_TIMESTAMP('2023-08-07 22:23:48'));
INSERT INTO ATTENDANCE(NO, MEMBER_NO, PRESENCE_TIME, LEAVE_TIME) VALUES(SEQ_ATTENDANCE_NO.NEXTVAL, 1, TO_TIMESTAMP('2023-08-08 09:00:10'), TO_TIMESTAMP('2023-08-08 19:18:57'));
INSERT INTO ATTENDANCE(NO, MEMBER_NO, PRESENCE_TIME, LEAVE_TIME) VALUES(SEQ_ATTENDANCE_NO.NEXTVAL, 1, TO_TIMESTAMP('2023-08-09 08:13:54'), TO_TIMESTAMP('2023-08-09 20:46:12'));
INSERT INTO ATTENDANCE(NO, MEMBER_NO, PRESENCE_TIME, LEAVE_TIME) VALUES(SEQ_ATTENDANCE_NO.NEXTVAL, 1, TO_TIMESTAMP('2023-08-10 07:50:12'), TO_TIMESTAMP('2023-08-10 18:12:12'));
INSERT INTO ATTENDANCE(NO, MEMBER_NO, PRESENCE_TIME, LEAVE_TIME) VALUES(SEQ_ATTENDANCE_NO.NEXTVAL, 1, TO_TIMESTAMP('2023-08-11 08:50:13'), TO_TIMESTAMP('2023-08-11 22:59:18'));
INSERT INTO ATTENDANCE(NO, MEMBER_NO, PRESENCE_TIME, LEAVE_TIME) VALUES(SEQ_ATTENDANCE_NO.NEXTVAL, 1, TO_TIMESTAMP('2023-08-14 08:45:18'), TO_TIMESTAMP('2023-08-14 23:14:12'));

INSERT INTO ATTENDANCE(NO, MEMBER_NO, PRESENCE_TIME, LEAVE_TIME) VALUES(SEQ_ATTENDANCE_NO.NEXTVAL, 2, TO_TIMESTAMP('2023-07-31 08:32:55'), TO_TIMESTAMP('2023-07-31 23:14:12'));
INSERT INTO ATTENDANCE(NO, MEMBER_NO, PRESENCE_TIME, LEAVE_TIME) VALUES(SEQ_ATTENDANCE_NO.NEXTVAL, 2, TO_TIMESTAMP('2023-08-01 08:01:05'), TO_TIMESTAMP('2023-08-01 18:10:17'));
INSERT INTO ATTENDANCE(NO, MEMBER_NO, PRESENCE_TIME, LEAVE_TIME) VALUES(SEQ_ATTENDANCE_NO.NEXTVAL, 2, TO_TIMESTAMP('2023-08-02 08:55:33'), TO_TIMESTAMP('2023-08-02 18:15:22'));
INSERT INTO ATTENDANCE(NO, MEMBER_NO, PRESENCE_TIME, LEAVE_TIME) VALUES(SEQ_ATTENDANCE_NO.NEXTVAL, 2, TO_TIMESTAMP('2023-08-03 09:01:22'), TO_TIMESTAMP('2023-08-03 18:25:39'));
INSERT INTO ATTENDANCE(NO, MEMBER_NO, PRESENCE_TIME, LEAVE_TIME) VALUES(SEQ_ATTENDANCE_NO.NEXTVAL, 2, TO_TIMESTAMP('2023-08-04 08:55:49'), TO_TIMESTAMP('2023-08-04 19:22:56'));
INSERT INTO ATTENDANCE(NO, MEMBER_NO, PRESENCE_TIME, LEAVE_TIME) VALUES(SEQ_ATTENDANCE_NO.NEXTVAL, 2, TO_TIMESTAMP('2023-08-07 08:23:11'), TO_TIMESTAMP('2023-08-07 22:23:48'));
INSERT INTO ATTENDANCE(NO, MEMBER_NO, PRESENCE_TIME, LEAVE_TIME) VALUES(SEQ_ATTENDANCE_NO.NEXTVAL, 2, TO_TIMESTAMP('2023-08-08 09:00:10'), TO_TIMESTAMP('2023-08-08 18:18:57'));
INSERT INTO ATTENDANCE(NO, MEMBER_NO, PRESENCE_TIME, LEAVE_TIME) VALUES(SEQ_ATTENDANCE_NO.NEXTVAL, 2, TO_TIMESTAMP('2023-08-09 08:45:54'), TO_TIMESTAMP('2023-08-09 20:46:12'));
INSERT INTO ATTENDANCE(NO, MEMBER_NO, PRESENCE_TIME, LEAVE_TIME) VALUES(SEQ_ATTENDANCE_NO.NEXTVAL, 2, TO_TIMESTAMP('2023-08-10 07:59:12'), TO_TIMESTAMP('2023-08-10 18:12:12'));
INSERT INTO ATTENDANCE(NO, MEMBER_NO, PRESENCE_TIME, LEAVE_TIME) VALUES(SEQ_ATTENDANCE_NO.NEXTVAL, 2, TO_TIMESTAMP('2023-08-11 08:15:13'), TO_TIMESTAMP('2023-08-11 20:59:18'));
INSERT INTO ATTENDANCE(NO, MEMBER_NO, PRESENCE_TIME, LEAVE_TIME) VALUES(SEQ_ATTENDANCE_NO.NEXTVAL, 2, TO_TIMESTAMP('2023-08-14 08:53:18'), TO_TIMESTAMP('2023-08-14 23:14:12'));
INSERT INTO ATTENDANCE(NO, MEMBER_NO, PRESENCE_TIME, STATUS) VALUES(SEQ_ATTENDANCE_NO.NEXTVAL, 15, TO_TIMESTAMP('2023-08-16 08:30:55'), 'O');


--당직
INSERT INTO "C##ALLISWELL"."DUTY" (NO, MEMBER_NO, DUTY_DAY) VALUES (SEQ_DUTY_NO.NEXTVAL, '1', TO_TIMESTAMP('2023-07-31', 'YYYY-MM-DD'));
INSERT INTO "C##ALLISWELL"."DUTY" (NO, MEMBER_NO, DUTY_DAY) VALUES (SEQ_DUTY_NO.NEXTVAL, '2', TO_TIMESTAMP('2023-08-01', 'YYYY-MM-DD'));
INSERT INTO "C##ALLISWELL"."DUTY" (NO, MEMBER_NO, DUTY_DAY) VALUES (SEQ_DUTY_NO.NEXTVAL, '3', TO_TIMESTAMP('2023-08-02', 'YYYY-MM-DD'));
INSERT INTO "C##ALLISWELL"."DUTY" (NO, MEMBER_NO, DUTY_DAY) VALUES (SEQ_DUTY_NO.NEXTVAL, '4', TO_TIMESTAMP('2023-08-03', 'YYYY-MM-DD'));
INSERT INTO "C##ALLISWELL"."DUTY" (NO, MEMBER_NO, DUTY_DAY) VALUES (SEQ_DUTY_NO.NEXTVAL, '21', TO_TIMESTAMP('2023-08-04', 'YYYY-MM-DD'));
INSERT INTO "C##ALLISWELL"."DUTY" (NO, MEMBER_NO, DUTY_DAY) VALUES (SEQ_DUTY_NO.NEXTVAL, '22', TO_TIMESTAMP('2023-08-05', 'YYYY-MM-DD'));
INSERT INTO "C##ALLISWELL"."DUTY" (NO, MEMBER_NO, DUTY_DAY) VALUES (SEQ_DUTY_NO.NEXTVAL, '10', TO_TIMESTAMP('2023-08-06', 'YYYY-MM-DD'));
INSERT INTO "C##ALLISWELL"."DUTY" (NO, MEMBER_NO, DUTY_DAY) VALUES (SEQ_DUTY_NO.NEXTVAL, '11', TO_TIMESTAMP('2023-08-07', 'YYYY-MM-DD'));
INSERT INTO "C##ALLISWELL"."DUTY" (NO, MEMBER_NO, DUTY_DAY) VALUES (SEQ_DUTY_NO.NEXTVAL, '12', TO_TIMESTAMP('2023-08-08', 'YYYY-MM-DD'));
INSERT INTO "C##ALLISWELL"."DUTY" (NO, MEMBER_NO, DUTY_DAY) VALUES (SEQ_DUTY_NO.NEXTVAL, '13', TO_TIMESTAMP('2023-08-09', 'YYYY-MM-DD'));
INSERT INTO "C##ALLISWELL"."DUTY" (NO, MEMBER_NO, DUTY_DAY) VALUES (SEQ_DUTY_NO.NEXTVAL, '19', TO_TIMESTAMP('2023-08-10', 'YYYY-MM-DD'));
INSERT INTO "C##ALLISWELL"."DUTY" (NO, MEMBER_NO, DUTY_DAY) VALUES (SEQ_DUTY_NO.NEXTVAL, '20', TO_TIMESTAMP('2023-08-11', 'YYYY-MM-DD'));
INSERT INTO "C##ALLISWELL"."DUTY" (NO, MEMBER_NO, DUTY_DAY) VALUES (SEQ_DUTY_NO.NEXTVAL, '28', TO_TIMESTAMP('2023-08-12', 'YYYY-MM-DD'));
INSERT INTO "C##ALLISWELL"."DUTY" (NO, MEMBER_NO, DUTY_DAY) VALUES (SEQ_DUTY_NO.NEXTVAL, '29', TO_TIMESTAMP('2023-08-13', 'YYYY-MM-DD'));
INSERT INTO "C##ALLISWELL"."DUTY" (NO, MEMBER_NO, DUTY_DAY) VALUES (SEQ_DUTY_NO.NEXTVAL, '30', TO_TIMESTAMP('2023-08-14', 'YYYY-MM-DD'));
INSERT INTO "C##ALLISWELL"."DUTY" (NO, MEMBER_NO, DUTY_DAY) VALUES (SEQ_DUTY_NO.NEXTVAL, '31', TO_TIMESTAMP('2023-08-15', 'YYYY-MM-DD'));


INSERT INTO "C##ALLISWELL"."DUTY" (NO, MEMBER_NO, DUTY_DAY) VALUES (SEQ_DUTY_NO.NEXTVAL, '5', TO_TIMESTAMP('2023-07-31', 'YYYY-MM-DD'));
INSERT INTO "C##ALLISWELL"."DUTY" (NO, MEMBER_NO, DUTY_DAY) VALUES (SEQ_DUTY_NO.NEXTVAL, '6', TO_TIMESTAMP('2023-08-01', 'YYYY-MM-DD'));
INSERT INTO "C##ALLISWELL"."DUTY" (NO, MEMBER_NO, DUTY_DAY) VALUES (SEQ_DUTY_NO.NEXTVAL, '7', TO_TIMESTAMP('2023-08-02', 'YYYY-MM-DD'));
INSERT INTO "C##ALLISWELL"."DUTY" (NO, MEMBER_NO, DUTY_DAY) VALUES (SEQ_DUTY_NO.NEXTVAL, '8', TO_TIMESTAMP('2023-08-03', 'YYYY-MM-DD'));
INSERT INTO "C##ALLISWELL"."DUTY" (NO, MEMBER_NO, DUTY_DAY) VALUES (SEQ_DUTY_NO.NEXTVAL, '9', TO_TIMESTAMP('2023-08-04', 'YYYY-MM-DD'));
INSERT INTO "C##ALLISWELL"."DUTY" (NO, MEMBER_NO, DUTY_DAY) VALUES (SEQ_DUTY_NO.NEXTVAL, '23', TO_TIMESTAMP('2023-08-05', 'YYYY-MM-DD'));
INSERT INTO "C##ALLISWELL"."DUTY" (NO, MEMBER_NO, DUTY_DAY) VALUES (SEQ_DUTY_NO.NEXTVAL, '24', TO_TIMESTAMP('2023-08-06', 'YYYY-MM-DD'));
INSERT INTO "C##ALLISWELL"."DUTY" (NO, MEMBER_NO, DUTY_DAY) VALUES (SEQ_DUTY_NO.NEXTVAL, '14', TO_TIMESTAMP('2023-08-07', 'YYYY-MM-DD'));
INSERT INTO "C##ALLISWELL"."DUTY" (NO, MEMBER_NO, DUTY_DAY) VALUES (SEQ_DUTY_NO.NEXTVAL, '15', TO_TIMESTAMP('2023-08-08', 'YYYY-MM-DD'));
INSERT INTO "C##ALLISWELL"."DUTY" (NO, MEMBER_NO, DUTY_DAY) VALUES (SEQ_DUTY_NO.NEXTVAL, '16', TO_TIMESTAMP('2023-08-09', 'YYYY-MM-DD'));
INSERT INTO "C##ALLISWELL"."DUTY" (NO, MEMBER_NO, DUTY_DAY) VALUES (SEQ_DUTY_NO.NEXTVAL, '17', TO_TIMESTAMP('2023-08-10', 'YYYY-MM-DD'));
INSERT INTO "C##ALLISWELL"."DUTY" (NO, MEMBER_NO, DUTY_DAY) VALUES (SEQ_DUTY_NO.NEXTVAL, '18', TO_TIMESTAMP('2023-08-11', 'YYYY-MM-DD'));
INSERT INTO "C##ALLISWELL"."DUTY" (NO, MEMBER_NO, DUTY_DAY) VALUES (SEQ_DUTY_NO.NEXTVAL, '25', TO_TIMESTAMP('2023-08-12', 'YYYY-MM-DD'));
INSERT INTO "C##ALLISWELL"."DUTY" (NO, MEMBER_NO, DUTY_DAY) VALUES (SEQ_DUTY_NO.NEXTVAL, '26', TO_TIMESTAMP('2023-08-13', 'YYYY-MM-DD'));
INSERT INTO "C##ALLISWELL"."DUTY" (NO, MEMBER_NO, DUTY_DAY) VALUES (SEQ_DUTY_NO.NEXTVAL, '27', TO_TIMESTAMP('2023-08-14', 'YYYY-MM-DD'));
INSERT INTO "C##ALLISWELL"."DUTY" (NO, MEMBER_NO, DUTY_DAY) VALUES (SEQ_DUTY_NO.NEXTVAL, '32', TO_TIMESTAMP('2023-08-15', 'YYYY-MM-DD'));

--PROCEEDING
INSERT INTO PROCEEDING (NO, MEMBER_NO, TITLE, CONTENT, STATUS, ENROLL_DATE) VALUES (SEQ_PROCEEDING_NO.NEXTVAL, 1, '제1차회의록', '제1차회의록내용입니다. 안건은 병원 현황 점검이고 결과는 이상없음 입니다.', 'O', '22/03/01 03:33:33');
INSERT INTO PROCEEDING (NO, MEMBER_NO, TITLE, CONTENT, STATUS, ENROLL_DATE) VALUES (SEQ_PROCEEDING_NO.NEXTVAL, 1, '제2차회의록', '제2차회의록내용입니다. 안건은 간호사 교육이고 결과는 해당 부서 과장 주도하에 기본 업무 교육 시행입니다.', 'O', '22/03/15 03:33:33');
INSERT INTO PROCEEDING (NO, MEMBER_NO, TITLE, CONTENT, STATUS, ENROLL_DATE) VALUES (SEQ_PROCEEDING_NO.NEXTVAL, 1, '제3차회의록', '제3차회의록내용입니다. 안건은 병원 현황 점검이고 결과는 이상없음 입니다.', 'O', '22/04/01 03:33:33');
INSERT INTO PROCEEDING (NO, MEMBER_NO, TITLE, CONTENT, STATUS, ENROLL_DATE) VALUES (SEQ_PROCEEDING_NO.NEXTVAL, 1, '제4차회의록', '제4차회의록내용입니다. 안건은 병원장 휴가기간 중 업무 대행 선출이고 결과는 외과 과장입니다.', 'O', '22/04/15 03:33:33');
INSERT INTO PROCEEDING (NO, MEMBER_NO, TITLE, CONTENT, STATUS, ENROLL_DATE) VALUES (SEQ_PROCEEDING_NO.NEXTVAL, 1, '제5차회의록', '제5차회의록내용입니다. 안건은 병원 현황 점검이고 결과는 이상없음 입니다.', 'O', '22/05/01 03:33:33');
INSERT INTO PROCEEDING (NO, MEMBER_NO, TITLE, CONTENT, STATUS, ENROLL_DATE) VALUES (SEQ_PROCEEDING_NO.NEXTVAL, 1, '제6차회의록', '제6차회의록내용입니다. 안건은 감염 예방 대책이고 결과는 손 소독제 배치 및 병원 내 마스크 필수 착용입니다.', 'O', '22/05/15 03:33:33');
INSERT INTO PROCEEDING (NO, MEMBER_NO, TITLE, CONTENT, STATUS, ENROLL_DATE) VALUES (SEQ_PROCEEDING_NO.NEXTVAL, 1, '제7차회의록', '제7차회의록내용입니다. 안건은 병원 현황 점검이고 결과는 이상없음 입니다.', 'O', '22/06/01 03:33:33');
INSERT INTO PROCEEDING (NO, MEMBER_NO, TITLE, CONTENT, STATUS, ENROLL_DATE) VALUES (SEQ_PROCEEDING_NO.NEXTVAL, 1, '제8차회의록', '제8차회의록내용입니다. 안건은 병원 현황 점검이고 결과는 이상없음 입니다.', 'O', '22/06/15 03:33:33');
INSERT INTO PROCEEDING (NO, MEMBER_NO, TITLE, CONTENT, STATUS, ENROLL_DATE) VALUES (SEQ_PROCEEDING_NO.NEXTVAL, 1, '제9차회의록', '제9차회의록내용입니다. 안건은 기본급 인상이고 결과는 과반수 이상 동의로 찬성 입니다.', 'O', '22/07/01 03:33:33');
INSERT INTO PROCEEDING (NO, MEMBER_NO, TITLE, CONTENT, STATUS, ENROLL_DATE) VALUES (SEQ_PROCEEDING_NO.NEXTVAL, 1, '제10차회의록', '제10차회의록내용입니다. 안건은 병원 현황 점검이고 결과는 이상없음 입니다.', 'O', '22/07/15 03:33:33');
INSERT INTO PROCEEDING (NO, MEMBER_NO, TITLE, CONTENT, STATUS, ENROLL_DATE) VALUES (SEQ_PROCEEDING_NO.NEXTVAL, 1, '제11차회의록', '제11차회의록내용입니다. 안건은 환자 안전을 위한 의료진 교육이고 결과는 0810진행 입니다.', 'O', '22/08/01 03:33:33');
INSERT INTO PROCEEDING (NO, MEMBER_NO, TITLE, CONTENT, STATUS, ENROLL_DATE) VALUES (SEQ_PROCEEDING_NO.NEXTVAL, 1, '제12차회의록', '제12차회의록내용입니다. 안건은 병원 현황 점검이고 결과는 이상없음 입니다.', 'O', '22/08/15 03:33:33');
INSERT INTO PROCEEDING (NO, MEMBER_NO, TITLE, CONTENT, STATUS, ENROLL_DATE) VALUES (SEQ_PROCEEDING_NO.NEXTVAL, 1, '제13차회의록', '제13차회의록내용입니다. 안건은 병원 현황 점검이고 결과는 이상없음 입니다.', 'O', '23/05/15 03:33:33');
INSERT INTO PROCEEDING (NO, MEMBER_NO, TITLE, CONTENT, STATUS, ENROLL_DATE) VALUES (SEQ_PROCEEDING_NO.NEXTVAL, 1, '제14차회의록', '제14차회의록내용입니다. 안건은 병원 시설 유지 보수 계획이고 결과는 담당자 점검 후 재논의입니다.', 'O', '23/06/01 03:33:33');
INSERT INTO PROCEEDING (NO, MEMBER_NO, TITLE, CONTENT, STATUS, ENROLL_DATE) VALUES (SEQ_PROCEEDING_NO.NEXTVAL, 1, '제15차회의록', '제15차회의록내용입니다. 안건은 병원 현황 점검이고 결과는 이상없음 입니다.', 'O', '23/06/15 03:33:33');
INSERT INTO PROCEEDING (NO, MEMBER_NO, TITLE, CONTENT, STATUS, ENROLL_DATE) VALUES (SEQ_PROCEEDING_NO.NEXTVAL, 1, '제16차회의록', '제16차회의록내용입니다. 안건은 당뇨병 관련 환자 치료 방안이고 결과는 담당의 검토 후 재논의입니다.', 'O', '23/07/01 03:33:33');
INSERT INTO PROCEEDING (NO, MEMBER_NO, TITLE, CONTENT, STATUS, ENROLL_DATE) VALUES (SEQ_PROCEEDING_NO.NEXTVAL, 1, '제17차회의록', '제17차회의록내용입니다. 안건은 병원 현황 점검이고 결과는 이상없음 입니다.', 'O', '23/07/15 03:33:33');
INSERT INTO PROCEEDING (NO, MEMBER_NO, TITLE, CONTENT, STATUS, ENROLL_DATE) VALUES (SEQ_PROCEEDING_NO.NEXTVAL, 1, '제18차회의록', '제18차회의록내용입니다. 안건은 의료 인력 증강 대책이고 결과는 예산 및 TO 초과로 인한 불가능입니다.', 'O', '23/08/01 03:33:33');
INSERT INTO PROCEEDING (NO, MEMBER_NO, TITLE, CONTENT, STATUS, ENROLL_DATE) VALUES (SEQ_PROCEEDING_NO.NEXTVAL, 1, '제19차회의록', '제19차회의록내용입니다. 안건은 병원 현황 점검이고 결과는 이상없음 입니다.', 'O', '23/08/15 03:33:33');

--MAIL
INSERT INTO
MAIL
(NO, MAIL_TITLE, MAIL_CONTENT, MAIL_ENROLL_DATE)
VALUES
(SEQ_MAIL_NO.NEXTVAL, '메일입니다.1', '내용입니다.1', SYSDATE);
INSERT INTO
MAIL
(NO, MAIL_TITLE, MAIL_CONTENT, MAIL_ENROLL_DATE)
VALUES
(SEQ_MAIL_NO.NEXTVAL, '메일입니다.2', '내용입니다.2', SYSDATE);
INSERT INTO
MAIL
(NO, MAIL_TITLE, MAIL_CONTENT, MAIL_ENROLL_DATE)
VALUES
(SEQ_MAIL_NO.NEXTVAL, '메일입니다.3', '내용입니다.3', SYSDATE);
INSERT INTO
MAIL
(NO, MAIL_TITLE, MAIL_CONTENT, MAIL_ENROLL_DATE)
VALUES
(SEQ_MAIL_NO.NEXTVAL, '메일입니다.4', '내용입니다.4', SYSDATE);
INSERT INTO
MAIL
(NO, MAIL_TITLE, MAIL_CONTENT, MAIL_ENROLL_DATE)
VALUES
(SEQ_MAIL_NO.NEXTVAL, '메일입니다.5', '내용입니다.5', SYSDATE);
INSERT INTO
MAIL
(NO, MAIL_TITLE, MAIL_CONTENT, MAIL_ENROLL_DATE)
VALUES
(SEQ_MAIL_NO.NEXTVAL, '메일입니다.6', '내용입니다.6', SYSDATE);
INSERT INTO
MAIL
(NO, MAIL_TITLE, MAIL_CONTENT, MAIL_ENROLL_DATE)
VALUES
(SEQ_MAIL_NO.NEXTVAL, '메일입니다.7', '내용입니다.7', SYSDATE);
INSERT INTO
MAIL
(NO, MAIL_TITLE, MAIL_CONTENT, MAIL_ENROLL_DATE)
VALUES
(SEQ_MAIL_NO.NEXTVAL, '메일입니다.8', '내용입니다.8', SYSDATE);
INSERT INTO
MAIL
(NO, MAIL_TITLE, MAIL_CONTENT, MAIL_ENROLL_DATE)
VALUES
(SEQ_MAIL_NO.NEXTVAL, '메일입니다.9', '내용입니다.9', SYSDATE);
INSERT INTO
MAIL
(NO, MAIL_TITLE, MAIL_CONTENT, MAIL_ENROLL_DATE)
VALUES
(SEQ_MAIL_NO.NEXTVAL, '메일입니다.10', '내용입니다.10', SYSDATE);

--MAIL_ATTACHMENT

--RECEIVER_MAIL
--INSERT INTO MAIL (NO, MAIL_TITLE, MAIL_CONTENT) VALUES (1, '메일제목1', '메일내용1');
INSERT INTO RECEIVER_MAIL (NO, RECEIVER_NO, MAIL_NO) VALUES (SEQ_RECEIVER_MAIL_NO.NEXTVAL, 1, 1);
INSERT INTO RECEIVER_MAIL (NO, RECEIVER_NO, MAIL_NO) VALUES (SEQ_RECEIVER_MAIL_NO.NEXTVAL, 1, 2);
INSERT INTO RECEIVER_MAIL (NO, RECEIVER_NO, MAIL_NO) VALUES (SEQ_RECEIVER_MAIL_NO.NEXTVAL, 1, 3);
INSERT INTO RECEIVER_MAIL (NO, RECEIVER_NO, MAIL_NO) VALUES (SEQ_RECEIVER_MAIL_NO.NEXTVAL, 1, 4);
INSERT INTO RECEIVER_MAIL (NO, RECEIVER_NO, MAIL_NO) VALUES (SEQ_RECEIVER_MAIL_NO.NEXTVAL, 1, 5);
INSERT INTO RECEIVER_MAIL (NO, RECEIVER_NO, MAIL_NO) VALUES (SEQ_RECEIVER_MAIL_NO.NEXTVAL, 1, 6);
INSERT INTO RECEIVER_MAIL (NO, RECEIVER_NO, MAIL_NO) VALUES (SEQ_RECEIVER_MAIL_NO.NEXTVAL, 1, 7);
INSERT INTO RECEIVER_MAIL (NO, RECEIVER_NO, MAIL_NO) VALUES (SEQ_RECEIVER_MAIL_NO.NEXTVAL, 1, 8);
INSERT INTO RECEIVER_MAIL (NO, RECEIVER_NO, MAIL_NO) VALUES (SEQ_RECEIVER_MAIL_NO.NEXTVAL, 1, 9);
INSERT INTO RECEIVER_MAIL (NO, RECEIVER_NO, MAIL_NO) VALUES (SEQ_RECEIVER_MAIL_NO.NEXTVAL, 1, 10);

--SENDER_MAIL
INSERT INTO SENDER_MAIL (NO, SENDER_NO, MAIL_NO) VALUES (SEQ_SENDER_MAIL_NO.NEXTVAL, 1, 1);
INSERT INTO SENDER_MAIL (NO, SENDER_NO, MAIL_NO) VALUES (SEQ_SENDER_MAIL_NO.NEXTVAL, 1, 2);
INSERT INTO SENDER_MAIL (NO, SENDER_NO, MAIL_NO) VALUES (SEQ_SENDER_MAIL_NO.NEXTVAL, 1, 3);
INSERT INTO SENDER_MAIL (NO, SENDER_NO, MAIL_NO) VALUES (SEQ_SENDER_MAIL_NO.NEXTVAL, 1, 4);
INSERT INTO SENDER_MAIL (NO, SENDER_NO, MAIL_NO) VALUES (SEQ_SENDER_MAIL_NO.NEXTVAL, 1, 5);
INSERT INTO SENDER_MAIL (NO, SENDER_NO, MAIL_NO) VALUES (SEQ_SENDER_MAIL_NO.NEXTVAL, 1, 6);
INSERT INTO SENDER_MAIL (NO, SENDER_NO, MAIL_NO) VALUES (SEQ_SENDER_MAIL_NO.NEXTVAL, 1, 7);
INSERT INTO SENDER_MAIL (NO, SENDER_NO, MAIL_NO) VALUES (SEQ_SENDER_MAIL_NO.NEXTVAL, 1, 8);
INSERT INTO SENDER_MAIL (NO, SENDER_NO, MAIL_NO) VALUES (SEQ_SENDER_MAIL_NO.NEXTVAL, 1, 9);
INSERT INTO SENDER_MAIL (NO, SENDER_NO, MAIL_NO) VALUES (SEQ_SENDER_MAIL_NO.NEXTVAL, 1, 10);

--더미데이터
--ADMIN
INSERT INTO ADMIN(NO, ADMIN_ID, ADMIN_PWD, ADMIN_NICK) VALUES(SEQ_ADMIN_NO.NEXTVAL, 'ADMIN', '1234', '관리자');

--NOTICE
INSERT INTO
NOTICE
(NO, WRITER_NO, TITLE, CONTENT)
VALUES
(SEQ_NOTICE_NO.NEXTVAL, 1, '내일도 모두 힙냅시다.', '오늘 하루가 힘들다고 포기하지 말고 모두들 홧팅');
INSERT INTO
NOTICE
(NO, WRITER_NO, TITLE, CONTENT)
VALUES
(SEQ_NOTICE_NO.NEXTVAL, 1, '오늘도 모두 힙냅시다.', '어제 하루가 힘들다고 포기하지 말고 모두들 홧팅');
INSERT INTO
NOTICE
(NO, WRITER_NO, TITLE, CONTENT)
VALUES
(SEQ_NOTICE_NO.NEXTVAL, 1, '안전수칙준수사항.', '안전한 하루 보내요');
INSERT INTO
NOTICE
(NO, WRITER_NO, TITLE, CONTENT)
VALUES
(SEQ_NOTICE_NO.NEXTVAL, 1, '카풀 인원 모집.', '카풀 인원 모집합니다.');
INSERT INTO
NOTICE
(NO, WRITER_NO, TITLE, CONTENT)
VALUES
(SEQ_NOTICE_NO.NEXTVAL, 1, '현재 병원내 의료사고가 발생.', '의료사고가 잦으므로 각별히 조심해주시기 바랍니다.');
INSERT INTO
NOTICE
(NO, WRITER_NO, TITLE, CONTENT)
VALUES
(SEQ_NOTICE_NO.NEXTVAL, 1, '흡연실 관련.', '병원 내 흡연은 불법이므로 병원 지부 밖에서 흡연해주시기 바랍니다.');
INSERT INTO
NOTICE
(NO, WRITER_NO, TITLE, CONTENT)
VALUES
(SEQ_NOTICE_NO.NEXTVAL, 1, '의료시설 관리.', '의료시설 뒷정리 및 의료폐기물 뒤처리를 확실히 해주시기 바랍니다.');
INSERT INTO
NOTICE
(NO, WRITER_NO, TITLE, CONTENT)
VALUES
(SEQ_NOTICE_NO.NEXTVAL, 1, '챗 GPT 사용관련', '병원에서 사용하는 문서 내용 등을 GPT에 작성 금지해주시기 바랍니다.');
INSERT INTO
NOTICE
(NO, WRITER_NO, TITLE, CONTENT)
VALUES
(SEQ_NOTICE_NO.NEXTVAL, 1, '진급자', '이번년도 진급자는 OOO, OOO, OOO씨 입니다.');
INSERT INTO
NOTICE
(NO, WRITER_NO, TITLE, CONTENT)
VALUES
(SEQ_NOTICE_NO.NEXTVAL, 1, '현재 전산문제 발생', '월급 지급이 늦어지고 있습니다. 많은 양해 부탁드립니다.');

--NOTICE_ATTACHMENT

--NOTICE_REPLY
INSERT INTO
NOTICE_REPLY
(NO, NOTICE_NO, WRITER_NO, CONTENT, ENROLL_DATE)
VALUES
(SEQ_NOTICE_REPLY_NO.NEXTVAL, 1, 1, '화....화이팅......', SYSDATE);
INSERT INTO
NOTICE_REPLY
(NO, NOTICE_NO, WRITER_NO, CONTENT, ENROLL_DATE)
VALUES
(SEQ_NOTICE_REPLY_NO.NEXTVAL, 1, 1, '어제는 진짜 바빴어요....', SYSDATE);
INSERT INTO
NOTICE_REPLY
(NO, NOTICE_NO, WRITER_NO, CONTENT, ENROLL_DATE)
VALUES
(SEQ_NOTICE_REPLY_NO.NEXTVAL, 1, 1, '첫째도 안전 둘째도 안전!', SYSDATE);
INSERT INTO
NOTICE_REPLY
(NO, NOTICE_NO, WRITER_NO, CONTENT, ENROLL_DATE)
VALUES
(SEQ_NOTICE_REPLY_NO.NEXTVAL, 1, 1, '저도 카풀 참여할래요', SYSDATE);
INSERT INTO
NOTICE_REPLY
(NO, NOTICE_NO, WRITER_NO, CONTENT, ENROLL_DATE)
VALUES
(SEQ_NOTICE_REPLY_NO.NEXTVAL, 1, 1, '의료사고는 진짜 위험해요', SYSDATE);
INSERT INTO
NOTICE_REPLY
(NO, NOTICE_NO, WRITER_NO, CONTENT, ENROLL_DATE)
VALUES
(SEQ_NOTICE_REPLY_NO.NEXTVAL, 1, 1, '흡연자들이 비흡연자들을 배려 안해줘요', SYSDATE);
INSERT INTO
NOTICE_REPLY
(NO, NOTICE_NO, WRITER_NO, CONTENT, ENROLL_DATE)
VALUES
(SEQ_NOTICE_REPLY_NO.NEXTVAL, 1, 1, '뒷정리를 깔끔히 해야 의료사고도 줄어들어요', SYSDATE);
INSERT INTO
NOTICE_REPLY
(NO, NOTICE_NO, WRITER_NO, CONTENT, ENROLL_DATE)
VALUES
(SEQ_NOTICE_REPLY_NO.NEXTVAL, 1, 1, '죄송합니다... 다음부터 사용 금하겠습니다.', SYSDATE);
INSERT INTO
NOTICE_REPLY
(NO, NOTICE_NO, WRITER_NO, CONTENT, ENROLL_DATE)
VALUES
(SEQ_NOTICE_REPLY_NO.NEXTVAL, 1, 1, '진급하신 분들 모두 축하드려요', SYSDATE);
INSERT INTO
NOTICE_REPLY
(NO, NOTICE_NO, WRITER_NO, CONTENT, ENROLL_DATE)
VALUES
(SEQ_NOTICE_REPLY_NO.NEXTVAL, 1, 1, '오늘 저녁에 치킨 먹을라고 했는데 아쉽네요 ㅠ', SYSDATE);

--SUGGESTIONS
INSERT INTO SUGGESTIONS (NO, MEMBER_NO, TITLE, CONTENT, SUGGESTION_STATUS) VALUES (SEQ_SUGGESTIONS_NO.NEXTVAL, 1, '쉬는시간', '쉬는시간이 15분씩 이였으면 좋겠어요', 'O');
INSERT INTO SUGGESTIONS (NO, MEMBER_NO, TITLE, CONTENT, SUGGESTION_STATUS) VALUES (SEQ_SUGGESTIONS_NO.NEXTVAL, 1, '셔틀버스', '셔틀버스 운영해주셨으면 좋겠어요', 'O');
INSERT INTO SUGGESTIONS (NO, MEMBER_NO, TITLE, CONTENT, SUGGESTION_STATUS) VALUES (SEQ_SUGGESTIONS_NO.NEXTVAL, 1, '건의사항', '건의할 거 알려주세요', 'O');
INSERT INTO SUGGESTIONS (NO, MEMBER_NO, TITLE, CONTENT, SUGGESTION_STATUS) VALUES (SEQ_SUGGESTIONS_NO.NEXTVAL, 1, '휴게실', '휴게실 자리 넓혀주세요', 'O');
INSERT INTO SUGGESTIONS (NO, MEMBER_NO, TITLE, CONTENT, SUGGESTION_STATUS) VALUES (SEQ_SUGGESTIONS_NO.NEXTVAL, 1, '집에 보내줘요', '집에가고싶다', 'O');
INSERT INTO SUGGESTIONS (NO, MEMBER_NO, TITLE, CONTENT, SUGGESTION_STATUS) VALUES (SEQ_SUGGESTIONS_NO.NEXTVAL, 1, '부조리', '부조리 개선해주세요', 'O');
INSERT INTO SUGGESTIONS (NO, MEMBER_NO, TITLE, CONTENT, SUGGESTION_STATUS) VALUES (SEQ_SUGGESTIONS_NO.NEXTVAL, 1, '휴지가 부족해요', '개인 휴지를 들고 다닐정도에요', 'O');
INSERT INTO SUGGESTIONS (NO, MEMBER_NO, TITLE, CONTENT, SUGGESTION_STATUS) VALUES (SEQ_SUGGESTIONS_NO.NEXTVAL, 1, '흡연장이 너무 멀어요', '흡연장 설치해주세요', 'O');
INSERT INTO SUGGESTIONS (NO, MEMBER_NO, TITLE, CONTENT, SUGGESTION_STATUS) VALUES (SEQ_SUGGESTIONS_NO.NEXTVAL, 1, '야근 싫어', '야근 없애주세요', 'O');
INSERT INTO SUGGESTIONS (NO, MEMBER_NO, TITLE, CONTENT, SUGGESTION_STATUS) VALUES (SEQ_SUGGESTIONS_NO.NEXTVAL, 1, '연봉 올려주세요', '너무 적어요', 'O');

--문의사항 게시판
INSERT INTO "C##ALLISWELL"."INQUIRY" (NO, MEMBER_NO, TITLE, CONTENT, ENROLL_DATE, MODIFY_DATE, INQUIRY_STATUS) VALUES (SEQ_INQUIRY_NO.NEXTVAL, '1', '월급 언제 들어와요?', '돈이 필요한데 월급이 언제 들어오는지 궁금해요', TO_TIMESTAMP('2023-07-17 20:04:56', 'YYYY-MM-DD HH24:MI:SS.FF'), TO_TIMESTAMP('2023-07-18 20:05:04', 'YYYY-MM-DD HH24:MI:SS.FF'), 'O');
INSERT INTO "C##ALLISWELL"."INQUIRY" (NO, MEMBER_NO, TITLE, CONTENT, ENROLL_DATE, MODIFY_DATE, INQUIRY_STATUS) VALUES (SEQ_INQUIRY_NO.NEXTVAL, '2', '휴가 관련 질문', '휴가 못쓰는 날이 있나요?', TO_TIMESTAMP('2023-07-17 20:04:56', 'YYYY-MM-DD HH24:MI:SS.FF'), TO_TIMESTAMP('2023-07-18 20:05:04', 'YYYY-MM-DD HH24:MI:SS.FF'), 'O');
INSERT INTO "C##ALLISWELL"."INQUIRY" (NO, MEMBER_NO, TITLE, CONTENT, ENROLL_DATE, MODIFY_DATE, INQUIRY_STATUS) VALUES (SEQ_INQUIRY_NO.NEXTVAL, '3', '2동 1층 화장실 변기가 막혔어요', '끝에 변기가 막혔어요 고쳐주세요', TO_TIMESTAMP('2023-07-17 20:04:56', 'YYYY-MM-DD HH24:MI:SS.FF'), TO_TIMESTAMP('2023-07-18 20:05:04', 'YYYY-MM-DD HH24:MI:SS.FF'), 'O');
INSERT INTO "C##ALLISWELL"."INQUIRY" (NO, MEMBER_NO, TITLE, CONTENT, ENROLL_DATE, MODIFY_DATE, INQUIRY_STATUS) VALUES (SEQ_INQUIRY_NO.NEXTVAL, '4', '무례한 환자는', '안받고 싶은데 그냥 내쫒으면 안되겠죠?', TO_TIMESTAMP('2023-07-17 20:04:56', 'YYYY-MM-DD HH24:MI:SS.FF'), TO_TIMESTAMP('2023-07-18 20:05:04', 'YYYY-MM-DD HH24:MI:SS.FF'), 'O');
INSERT INTO "C##ALLISWELL"."INQUIRY" (NO, MEMBER_NO, TITLE, CONTENT, ENROLL_DATE, MODIFY_DATE, INQUIRY_STATUS) VALUES (SEQ_INQUIRY_NO.NEXTVAL, '5', '관리자님 꼭 봐주세요', '미안하다 이거 보여주려고 어그로 끌었다', TO_TIMESTAMP('2023-07-17 20:04:56', 'YYYY-MM-DD HH24:MI:SS.FF'), TO_TIMESTAMP('2023-07-18 20:05:04', 'YYYY-MM-DD HH24:MI:SS.FF'), 'O');
INSERT INTO "C##ALLISWELL"."INQUIRY" (NO, MEMBER_NO, TITLE, CONTENT, ENROLL_DATE, MODIFY_DATE, INQUIRY_STATUS) VALUES (SEQ_INQUIRY_NO.NEXTVAL, '6', '건의사항 댓글', '건의사항은 댓글 안 달아주시나요?', TO_TIMESTAMP('2023-07-17 20:04:56', 'YYYY-MM-DD HH24:MI:SS.FF'), TO_TIMESTAMP('2023-07-18 20:05:04', 'YYYY-MM-DD HH24:MI:SS.FF'), 'X');
INSERT INTO "C##ALLISWELL"."INQUIRY" (NO, MEMBER_NO, TITLE, CONTENT, ENROLL_DATE, MODIFY_DATE, INQUIRY_STATUS) VALUES (SEQ_INQUIRY_NO.NEXTVAL, '7', '환자 명단이 안보여요', '환자 명단이 안보이는데 원래 안보이나요?', TO_TIMESTAMP('2023-07-17 20:04:56', 'YYYY-MM-DD HH24:MI:SS.FF'), TO_TIMESTAMP('2023-07-18 20:05:04', 'YYYY-MM-DD HH24:MI:SS.FF'), 'X');
INSERT INTO "C##ALLISWELL"."INQUIRY" (NO, MEMBER_NO, TITLE, CONTENT, ENROLL_DATE, MODIFY_DATE, INQUIRY_STATUS) VALUES (SEQ_INQUIRY_NO.NEXTVAL, '8', '사무실 번호', '사무실 번호가 없는 번호라는데요?', TO_TIMESTAMP('2023-07-17 20:04:56', 'YYYY-MM-DD HH24:MI:SS.FF'), TO_TIMESTAMP('2023-07-18 20:05:04', 'YYYY-MM-DD HH24:MI:SS.FF'), 'X');
INSERT INTO "C##ALLISWELL"."INQUIRY" (NO, MEMBER_NO, TITLE, CONTENT, ENROLL_DATE, MODIFY_DATE, INQUIRY_STATUS) VALUES (SEQ_INQUIRY_NO.NEXTVAL, '9', '승진은 언제 될까요?', '빨리 승진하고싶어요ㅎㅎㅎ', TO_TIMESTAMP('2023-07-17 20:04:56', 'YYYY-MM-DD HH24:MI:SS.FF'), TO_TIMESTAMP('2023-07-18 20:05:04', 'YYYY-MM-DD HH24:MI:SS.FF'), 'X');
INSERT INTO "C##ALLISWELL"."INQUIRY" (NO, MEMBER_NO, TITLE, CONTENT, ENROLL_DATE, MODIFY_DATE, INQUIRY_STATUS) VALUES (SEQ_INQUIRY_NO.NEXTVAL, '10', '흡연실 없애주세요', '흡연실 있는곳에 지나갈 일이 많은데 냄새가 심해요', TO_TIMESTAMP('2023-07-17 20:04:56', 'YYYY-MM-DD HH24:MI:SS.FF'), TO_TIMESTAMP('2023-07-18 20:05:04', 'YYYY-MM-DD HH24:MI:SS.FF'), 'X');

--문의사항 댓글
INSERT INTO "C##ALLISWELL"."INQUIRY_REPLY" (NO, INQUIRY_NO, ADMIN_NO, CONTENT, ENROLL_DATE, DELETE_YN) VALUES (SEQ_INQUIRY_REPLY_NO.NEXTVAL, '1', '1', '매월 1일에 들어옵니다', TO_TIMESTAMP('2023-07-17 20:26:38', 'YYYY-MM-DD HH24:MI:SS.FF'), 'N');
INSERT INTO "C##ALLISWELL"."INQUIRY_REPLY" (NO, INQUIRY_NO, ADMIN_NO, CONTENT, ENROLL_DATE, DELETE_YN) VALUES (SEQ_INQUIRY_REPLY_NO.NEXTVAL, '2', '1', '없습니다.', TO_TIMESTAMP('2023-07-17 20:29:36', 'YYYY-MM-DD HH24:MI:SS.FF'), 'N');
INSERT INTO "C##ALLISWELL"."INQUIRY_REPLY" (NO, INQUIRY_NO, ADMIN_NO, CONTENT, ENROLL_DATE, DELETE_YN) VALUES (SEQ_INQUIRY_REPLY_NO.NEXTVAL, '3', '1', '빠른 시일내에 고치겠습니다', TO_TIMESTAMP('2023-07-17 20:29:39', 'YYYY-MM-DD HH24:MI:SS.FF'), 'N');
INSERT INTO "C##ALLISWELL"."INQUIRY_REPLY" (NO, INQUIRY_NO, ADMIN_NO, CONTENT, ENROLL_DATE, DELETE_YN) VALUES (SEQ_INQUIRY_REPLY_NO.NEXTVAL, '4', '1', '최대한 참아주세요', TO_TIMESTAMP('2023-07-17 20:29:41', 'YYYY-MM-DD HH24:MI:SS.FF'), 'N');
INSERT INTO "C##ALLISWELL"."INQUIRY_REPLY" (NO, INQUIRY_NO, ADMIN_NO, CONTENT, ENROLL_DATE, DELETE_YN) VALUES (SEQ_INQUIRY_REPLY_NO.NEXTVAL, '5', '1', '어그로는 바로 차단입니다.', TO_TIMESTAMP('2023-07-17 20:29:44', 'YYYY-MM-DD HH24:MI:SS.FF'), 'N');
INSERT INTO "C##ALLISWELL"."INQUIRY_REPLY" (NO, INQUIRY_NO, ADMIN_NO, CONTENT, ENROLL_DATE, DELETE_YN) VALUES (SEQ_INQUIRY_REPLY_NO.NEXTVAL, '6', '1', '건의사항은 댓글기능이 없습니다.', TO_TIMESTAMP('2023-07-17 20:29:46', 'YYYY-MM-DD HH24:MI:SS.FF'), 'N');
INSERT INTO "C##ALLISWELL"."INQUIRY_REPLY" (NO, INQUIRY_NO, ADMIN_NO, CONTENT, ENROLL_DATE, DELETE_YN) VALUES (SEQ_INQUIRY_REPLY_NO.NEXTVAL, '7', '1', '환자명단은 조회가 가능합니다. 한번더 확인해주세요.', TO_TIMESTAMP('2023-07-17 20:29:48', 'YYYY-MM-DD HH24:MI:SS.FF'), 'N');
INSERT INTO "C##ALLISWELL"."INQUIRY_REPLY" (NO, INQUIRY_NO, ADMIN_NO, CONTENT, ENROLL_DATE, DELETE_YN) VALUES (SEQ_INQUIRY_REPLY_NO.NEXTVAL, '8', '1', '수정하였습니다.', TO_TIMESTAMP('2023-07-17 20:29:48', 'YYYY-MM-DD HH24:MI:SS.FF'), 'N');
INSERT INTO "C##ALLISWELL"."INQUIRY_REPLY" (NO, INQUIRY_NO, ADMIN_NO, CONTENT, ENROLL_DATE, DELETE_YN) VALUES (SEQ_INQUIRY_REPLY_NO.NEXTVAL, '9', '1', '열심히 일하시면 됩니다.', TO_TIMESTAMP('2023-07-17 20:29:48', 'YYYY-MM-DD HH24:MI:SS.FF'), 'N');
INSERT INTO "C##ALLISWELL"."INQUIRY_REPLY" (NO, INQUIRY_NO, ADMIN_NO, CONTENT, ENROLL_DATE, DELETE_YN) VALUES (SEQ_INQUIRY_REPLY_NO.NEXTVAL, '10', '1', '안됩니다.', TO_TIMESTAMP('2023-07-17 20:29:48', 'YYYY-MM-DD HH24:MI:SS.FF'), 'N');
INSERT INTO "C##ALLISWELL"."INQUIRY_REPLY" (NO, INQUIRY_NO, ADMIN_NO, CONTENT, ENROLL_DATE, DELETE_YN) VALUES (SEQ_INQUIRY_REPLY_NO.NEXTVAL, '10', '1', '안됩니다.', TO_TIMESTAMP('2023-07-17 20:29:48', 'YYYY-MM-DD HH24:MI:SS.FF'), 'N');

--PATIENT
INSERT INTO PATIENT (NO,NAME,GENDER,REGISTRATION_NUMBER,PHONE_NUMBER,EMAIL)VALUES( SEQ_PATIENT_NO.NEXTVAL , '강백호' , 'M' , '9910101178965' , '01057963553' , 'junsub@naver.com');
INSERT INTO PATIENT (NO,NAME,GENDER,REGISTRATION_NUMBER,PHONE_NUMBER,EMAIL)VALUES( SEQ_PATIENT_NO.NEXTVAL , '강모동' , 'M' , '0510101178965' , '01057963553' , 'junsub@naver.com');
INSERT INTO PATIENT (NO,NAME,GENDER,REGISTRATION_NUMBER,PHONE_NUMBER,EMAIL)VALUES( SEQ_PATIENT_NO.NEXTVAL , '이숙은' , 'M' , '1110101178965' , '01057963553' , 'junsub@naver.com');
INSERT INTO PATIENT (NO,NAME,GENDER,REGISTRATION_NUMBER,PHONE_NUMBER,EMAIL)VALUES( SEQ_PATIENT_NO.NEXTVAL , '금지원' , 'M' , '7010101178965' , '01057963553' , 'junsub@naver.com');
INSERT INTO PATIENT (NO,NAME,GENDER,REGISTRATION_NUMBER,PHONE_NUMBER,EMAIL)VALUES( SEQ_PATIENT_NO.NEXTVAL , '박진구' , 'M' , '5810101178965' , '01057963553' , 'junsub@naver.com');
INSERT INTO PATIENT (NO,NAME,GENDER,REGISTRATION_NUMBER,PHONE_NUMBER,EMAIL)VALUES( SEQ_PATIENT_NO.NEXTVAL , '김구섭' , 'F' , '4810101178965' , '01057963553' , 'junsub@naver.com');
INSERT INTO PATIENT (NO,NAME,GENDER,REGISTRATION_NUMBER,PHONE_NUMBER,EMAIL)VALUES( SEQ_PATIENT_NO.NEXTVAL , '오일남' , 'F' , '5510101178965' , '01057963553' , 'junsub@naver.com');
INSERT INTO PATIENT (NO,NAME,GENDER,REGISTRATION_NUMBER,PHONE_NUMBER,EMAIL)VALUES( SEQ_PATIENT_NO.NEXTVAL , '왕일섭' , 'F' , '7710101178965' , '01057963553' , 'junsub@naver.com');
INSERT INTO PATIENT (NO,NAME,GENDER,REGISTRATION_NUMBER,PHONE_NUMBER,EMAIL)VALUES( SEQ_PATIENT_NO.NEXTVAL , '지준환' , 'F' , '9410101178965' , '01057963553' , 'junsub@naver.com');
INSERT INTO PATIENT (NO,NAME,GENDER,REGISTRATION_NUMBER,PHONE_NUMBER,EMAIL)VALUES( SEQ_PATIENT_NO.NEXTVAL , '오은빈' , 'F' , '6710101178965' , '01057963553' , 'junsub@naver.com');

--PRESCRIPTION
INSERT INTO PRESCRIPTION (NO, PATIENT_NO) VALUES (SEQ_PRESCRIPTION_LIST_NO.NEXTVAL, 1);
INSERT INTO PRESCRIPTION (NO, PATIENT_NO) VALUES (SEQ_PRESCRIPTION_LIST_NO.NEXTVAL, 2);
INSERT INTO PRESCRIPTION (NO, PATIENT_NO) VALUES (SEQ_PRESCRIPTION_LIST_NO.NEXTVAL, 3);
INSERT INTO PRESCRIPTION (NO, PATIENT_NO) VALUES (SEQ_PRESCRIPTION_LIST_NO.NEXTVAL, 4);
INSERT INTO PRESCRIPTION (NO, PATIENT_NO) VALUES (SEQ_PRESCRIPTION_LIST_NO.NEXTVAL, 5);
INSERT INTO PRESCRIPTION (NO, PATIENT_NO) VALUES (SEQ_PRESCRIPTION_LIST_NO.NEXTVAL, 6);
INSERT INTO PRESCRIPTION (NO, PATIENT_NO) VALUES (SEQ_PRESCRIPTION_LIST_NO.NEXTVAL, 7);
INSERT INTO PRESCRIPTION (NO, PATIENT_NO) VALUES (SEQ_PRESCRIPTION_LIST_NO.NEXTVAL, 8);
INSERT INTO PRESCRIPTION (NO, PATIENT_NO) VALUES (SEQ_PRESCRIPTION_LIST_NO.NEXTVAL, 9);
INSERT INTO PRESCRIPTION (NO, PATIENT_NO) VALUES (SEQ_PRESCRIPTION_LIST_NO.NEXTVAL, 10);

--PRESCRIPTION_LIST
INSERT INTO PRESCRIPTION_LIST (NO, PRESCRIPTION_NO, MEDICINE, TOTAL_DAY, DOSE, USAGE, NAME) VALUES (SEQ_PRESCRIPTION_NO.NEXTVAL, '1', '감기약', '3', '3알', '식후30분', '송준섭');
INSERT INTO PRESCRIPTION_LIST (NO, PRESCRIPTION_NO, MEDICINE, TOTAL_DAY, DOSE, USAGE, NAME) VALUES (SEQ_PRESCRIPTION_NO.NEXTVAL, '2', '감기약', '3', '3알', '식후30분', '송일섭');
INSERT INTO PRESCRIPTION_LIST (NO, PRESCRIPTION_NO, MEDICINE, TOTAL_DAY, DOSE, USAGE, NAME) VALUES (SEQ_PRESCRIPTION_NO.NEXTVAL, '3', '감기약', '3', '5알', '식후30분', '송이섭');
INSERT INTO PRESCRIPTION_LIST (NO, PRESCRIPTION_NO, MEDICINE, TOTAL_DAY, DOSE, USAGE, NAME) VALUES (SEQ_PRESCRIPTION_NO.NEXTVAL, '4', '감기약', '5', '3알', '식전30분', '송삼섭');
INSERT INTO PRESCRIPTION_LIST (NO, PRESCRIPTION_NO, MEDICINE, TOTAL_DAY, DOSE, USAGE, NAME) VALUES (SEQ_PRESCRIPTION_NO.NEXTVAL, '5', '감기약', '5', '3알', '식전30분', '송사섭');
INSERT INTO PRESCRIPTION_LIST (NO, PRESCRIPTION_NO, MEDICINE, TOTAL_DAY, DOSE, USAGE, NAME) VALUES (SEQ_PRESCRIPTION_NO.NEXTVAL, '6', '감기약', '5', '3알', '식전30분', '송오섭');
INSERT INTO PRESCRIPTION_LIST (NO, PRESCRIPTION_NO, MEDICINE, TOTAL_DAY, DOSE, USAGE, NAME) VALUES (SEQ_PRESCRIPTION_NO.NEXTVAL, '7', '진통제', '7', '3알', '아침', '송육섭');
INSERT INTO PRESCRIPTION_LIST (NO, PRESCRIPTION_NO, MEDICINE, TOTAL_DAY, DOSE, USAGE, NAME) VALUES (SEQ_PRESCRIPTION_NO.NEXTVAL, '8', '진통제', '7', '3알', '아침', '송칠섭');
INSERT INTO PRESCRIPTION_LIST (NO, PRESCRIPTION_NO, MEDICINE, TOTAL_DAY, DOSE, USAGE, NAME) VALUES (SEQ_PRESCRIPTION_NO.NEXTVAL, '9', '소염제', '10', '3알', '자기전', '송팔섭');
INSERT INTO PRESCRIPTION_LIST (NO, PRESCRIPTION_NO, MEDICINE, TOTAL_DAY, DOSE, USAGE, NAME) VALUES (SEQ_PRESCRIPTION_NO.NEXTVAL, '10', '소염제', '10', '3알', '자기전', '송구섭');

--OPERATING_ROOM
INSERT INTO
OPERATING_ROOM
(NO, STATUS, LOCATION)
VALUES
(SEQ_OPERATING_ROOM_NO.NEXTVAL, 'O', '3동 101호');
INSERT INTO
OPERATING_ROOM
(NO, STATUS, LOCATION)
VALUES
(SEQ_OPERATING_ROOM_NO.NEXTVAL, 'O', '3동 102호');
INSERT INTO
OPERATING_ROOM
(NO, STATUS, LOCATION)
VALUES
(SEQ_OPERATING_ROOM_NO.NEXTVAL, 'O', '3동 103호');
INSERT INTO
OPERATING_ROOM
(NO, STATUS, LOCATION)
VALUES
(SEQ_OPERATING_ROOM_NO.NEXTVAL, 'X', '3동 104호');
INSERT INTO
OPERATING_ROOM
(NO, STATUS, LOCATION)
VALUES
(SEQ_OPERATING_ROOM_NO.NEXTVAL, 'X', '3동 105호');
INSERT INTO
OPERATING_ROOM
(NO, STATUS, LOCATION)
VALUES
(SEQ_OPERATING_ROOM_NO.NEXTVAL, 'O', '3동 106호');
INSERT INTO
OPERATING_ROOM
(NO, STATUS, LOCATION)
VALUES
(SEQ_OPERATING_ROOM_NO.NEXTVAL, 'O', '4동 101호');
INSERT INTO
OPERATING_ROOM
(NO, STATUS, LOCATION)
VALUES
(SEQ_OPERATING_ROOM_NO.NEXTVAL, 'O', '4동 102호');
INSERT INTO
OPERATING_ROOM
(NO, STATUS, LOCATION)
VALUES
(SEQ_OPERATING_ROOM_NO.NEXTVAL, 'X', '4동 103호');
INSERT INTO
OPERATING_ROOM
(NO, STATUS, LOCATION)
VALUES
(SEQ_OPERATING_ROOM_NO.NEXTVAL, 'X', '4동 104호');


--OPERATION_SCHEDULE
INSERT INTO
OPERATION_SCHEDULE
(NO, OPERATING_ROOM_NO, PATIENT_NO, OPERATION_NAME, START_DATE, END_DATE, STATUS)
VALUES
(SEQ_OPERATION_SCHEDULE_NO.NEXTVAL, 1, 1, '간암수술', SYSDATE, SYSDATE, 'O');
INSERT INTO
OPERATION_SCHEDULE
(NO, OPERATING_ROOM_NO, PATIENT_NO, OPERATION_NAME, START_DATE, END_DATE, STATUS)
VALUES
(SEQ_OPERATION_SCHEDULE_NO.NEXTVAL, 2, 2, '골절수술', SYSDATE, SYSDATE, 'O');
INSERT INTO
OPERATION_SCHEDULE
(NO, OPERATING_ROOM_NO, PATIENT_NO, OPERATION_NAME, START_DATE, END_DATE, STATUS)
VALUES
(SEQ_OPERATION_SCHEDULE_NO.NEXTVAL, 3, 3, '절개수술', SYSDATE, SYSDATE, 'O');
INSERT INTO
OPERATION_SCHEDULE
(NO, OPERATING_ROOM_NO, PATIENT_NO, OPERATION_NAME, START_DATE, END_DATE, STATUS)
VALUES
(SEQ_OPERATION_SCHEDULE_NO.NEXTVAL, 6, 4, '심장수술', SYSDATE, SYSDATE, 'O');
INSERT INTO
OPERATION_SCHEDULE
(NO, OPERATING_ROOM_NO, PATIENT_NO, OPERATION_NAME, START_DATE, END_DATE, STATUS)
VALUES
(SEQ_OPERATION_SCHEDULE_NO.NEXTVAL, 7, 5, '담낭염수술', SYSDATE, SYSDATE, 'O');
INSERT INTO
OPERATION_SCHEDULE
(NO, OPERATING_ROOM_NO, PATIENT_NO, OPERATION_NAME, START_DATE, END_DATE, STATUS)
VALUES
(SEQ_OPERATION_SCHEDULE_NO.NEXTVAL, 8, 6, '신장이식수술', SYSDATE, SYSDATE, 'O');
INSERT INTO
OPERATION_SCHEDULE
(NO, OPERATING_ROOM_NO, PATIENT_NO, OPERATION_NAME, START_DATE, END_DATE, STATUS)
VALUES
(SEQ_OPERATION_SCHEDULE_NO.NEXTVAL, 7, 1, '골격핵수술', SYSDATE, SYSDATE, 'O');
INSERT INTO
OPERATION_SCHEDULE
(NO, OPERATING_ROOM_NO, PATIENT_NO, OPERATION_NAME, START_DATE, END_DATE, STATUS)
VALUES
(SEQ_OPERATION_SCHEDULE_NO.NEXTVAL, 8, 1, '모발이식수술', SYSDATE, SYSDATE, 'O');
INSERT INTO
OPERATION_SCHEDULE
(NO, OPERATING_ROOM_NO, PATIENT_NO, OPERATION_NAME, START_DATE, END_DATE, STATUS)
VALUES
(SEQ_OPERATION_SCHEDULE_NO.NEXTVAL, 9, 1, '피부이식수술', SYSDATE, SYSDATE, 'O');
INSERT INTO
OPERATION_SCHEDULE
(NO, OPERATING_ROOM_NO, PATIENT_NO, OPERATION_NAME, START_DATE, END_DATE, STATUS)
VALUES
(SEQ_OPERATION_SCHEDULE_NO.NEXTVAL, 10, 1, '신경봉합술', SYSDATE, SYSDATE, 'O');

--PARTICIPANT
INSERT INTO PARTICIPANT(NO, PARTICIPANT_NO, OPERATION_SCHEDULE_NO) VALUES(SEQ_PARTICIPANT_NO.NEXTVAL, 1, 1);
INSERT INTO PARTICIPANT(NO, PARTICIPANT_NO, OPERATION_SCHEDULE_NO) VALUES(SEQ_PARTICIPANT_NO.NEXTVAL, 2, 1);
INSERT INTO PARTICIPANT(NO, PARTICIPANT_NO, OPERATION_SCHEDULE_NO) VALUES(SEQ_PARTICIPANT_NO.NEXTVAL, 3, 1);
INSERT INTO PARTICIPANT(NO, PARTICIPANT_NO, OPERATION_SCHEDULE_NO) VALUES(SEQ_PARTICIPANT_NO.NEXTVAL, 4, 1);
INSERT INTO PARTICIPANT(NO, PARTICIPANT_NO, OPERATION_SCHEDULE_NO) VALUES(SEQ_PARTICIPANT_NO.NEXTVAL, 5, 1);
INSERT INTO PARTICIPANT(NO, PARTICIPANT_NO, OPERATION_SCHEDULE_NO) VALUES(SEQ_PARTICIPANT_NO.NEXTVAL, 6, 2);
INSERT INTO PARTICIPANT(NO, PARTICIPANT_NO, OPERATION_SCHEDULE_NO) VALUES(SEQ_PARTICIPANT_NO.NEXTVAL, 7, 2);
INSERT INTO PARTICIPANT(NO, PARTICIPANT_NO, OPERATION_SCHEDULE_NO) VALUES(SEQ_PARTICIPANT_NO.NEXTVAL, 8, 2);
INSERT INTO PARTICIPANT(NO, PARTICIPANT_NO, OPERATION_SCHEDULE_NO) VALUES(SEQ_PARTICIPANT_NO.NEXTVAL, 9, 2);
INSERT INTO PARTICIPANT(NO, PARTICIPANT_NO, OPERATION_SCHEDULE_NO) VALUES(SEQ_PARTICIPANT_NO.NEXTVAL, 10, 2);


--RECEIPT
INSERT INTO RECEIPT (NO, PATIENT_NO, SYMPTOM) VALUES (SEQ_RECEIPT_NO.NEXTVAL, 1, '감기몸살');
INSERT INTO RECEIPT (NO, PATIENT_NO, SYMPTOM) VALUES (SEQ_RECEIPT_NO.NEXTVAL, 2, '감기몸살');
INSERT INTO RECEIPT (NO, PATIENT_NO, SYMPTOM) VALUES (SEQ_RECEIPT_NO.NEXTVAL, 3, '감기몸살');
INSERT INTO RECEIPT (NO, PATIENT_NO, SYMPTOM) VALUES (SEQ_RECEIPT_NO.NEXTVAL, 4, '감기몸살');
INSERT INTO RECEIPT (NO, PATIENT_NO, SYMPTOM) VALUES (SEQ_RECEIPT_NO.NEXTVAL, 5, '감기몸살');
INSERT INTO RECEIPT (NO, PATIENT_NO, SYMPTOM) VALUES (SEQ_RECEIPT_NO.NEXTVAL, 6, '감기몸살');
INSERT INTO RECEIPT (NO, PATIENT_NO, SYMPTOM) VALUES (SEQ_RECEIPT_NO.NEXTVAL, 7, '두통');
INSERT INTO RECEIPT (NO, PATIENT_NO, SYMPTOM) VALUES (SEQ_RECEIPT_NO.NEXTVAL, 8, '치통');
INSERT INTO RECEIPT (NO, PATIENT_NO, SYMPTOM) VALUES (SEQ_RECEIPT_NO.NEXTVAL, 9, '찢어진상처');
INSERT INTO RECEIPT (NO, PATIENT_NO, SYMPTOM) VALUES (SEQ_RECEIPT_NO.NEXTVAL, 10, '베인상처');

--진료
INSERT INTO "C##ALLISWELL"."DIAGNOSIS" (RECEIPT_NO, DAY, MEDICAL_RECORD) VALUES (SEQ_DIAGNOSIS_NO.NEXTVAL, TO_TIMESTAMP('2023-07-17 19:25:56.372450800', 'YYYY-MM-DD HH24:MI:SS.FF'), '감기로 보여서 약을 처방함');
INSERT INTO "C##ALLISWELL"."DIAGNOSIS" (RECEIPT_NO, DAY, MEDICAL_RECORD) VALUES (SEQ_DIAGNOSIS_NO.NEXTVAL, TO_TIMESTAMP('2023-07-17 19:25:56.372450800', 'YYYY-MM-DD HH24:MI:SS.FF'), '진단 결과 이상 없음');
INSERT INTO "C##ALLISWELL"."DIAGNOSIS" (RECEIPT_NO, DAY, MEDICAL_RECORD) VALUES (SEQ_DIAGNOSIS_NO.NEXTVAL, TO_TIMESTAMP('2023-07-17 19:25:56.372450800', 'YYYY-MM-DD HH24:MI:SS.FF'), '독감으로 보여서 주사맞아야함');
INSERT INTO "C##ALLISWELL"."DIAGNOSIS" (RECEIPT_NO, DAY, MEDICAL_RECORD) VALUES (SEQ_DIAGNOSIS_NO.NEXTVAL, TO_TIMESTAMP('2023-07-17 19:25:56.372450800', 'YYYY-MM-DD HH24:MI:SS.FF'), '콧물과 기침이 심함 약을 처방함');
INSERT INTO "C##ALLISWELL"."DIAGNOSIS" (RECEIPT_NO, DAY, MEDICAL_RECORD) VALUES (SEQ_DIAGNOSIS_NO.NEXTVAL, TO_TIMESTAMP('2023-07-17 19:25:56.372450800', 'YYYY-MM-DD HH24:MI:SS.FF'), '열이심하게 나서 약을 처방함');
INSERT INTO "C##ALLISWELL"."DIAGNOSIS" (RECEIPT_NO, DAY, MEDICAL_RECORD) VALUES (SEQ_DIAGNOSIS_NO.NEXTVAL, TO_TIMESTAMP('2023-07-17 19:25:56.372450800', 'YYYY-MM-DD HH24:MI:SS.FF'), '목이 약간 부었음 약을 처방함');
INSERT INTO "C##ALLISWELL"."DIAGNOSIS" (RECEIPT_NO, DAY, MEDICAL_RECORD) VALUES (SEQ_DIAGNOSIS_NO.NEXTVAL, TO_TIMESTAMP('2023-07-17 19:25:56.372450800', 'YYYY-MM-DD HH24:MI:SS.FF'), '열이 너무 심함 큰병원에 진료 희망');
INSERT INTO "C##ALLISWELL"."DIAGNOSIS" (RECEIPT_NO, DAY, MEDICAL_RECORD) VALUES (SEQ_DIAGNOSIS_NO.NEXTVAL, TO_TIMESTAMP('2023-07-17 19:25:56.372450800', 'YYYY-MM-DD HH24:MI:SS.FF'), '몸살 감기로 보임 약처방');
INSERT INTO "C##ALLISWELL"."DIAGNOSIS" (RECEIPT_NO, DAY, MEDICAL_RECORD) VALUES (SEQ_DIAGNOSIS_NO.NEXTVAL, TO_TIMESTAMP('2023-07-17 19:25:56.372450800', 'YYYY-MM-DD HH24:MI:SS.FF'), '암튼 약처방');
INSERT INTO "C##ALLISWELL"."DIAGNOSIS" (RECEIPT_NO, DAY, MEDICAL_RECORD) VALUES (SEQ_DIAGNOSIS_NO.NEXTVAL, TO_TIMESTAMP('2023-07-17 19:25:56.372450800', 'YYYY-MM-DD HH24:MI:SS.FF'), '생명의 위험을 느낌 바로 응급실로 가야함');

--입원실
INSERT INTO "C##ALLISWELL"."INPATIENT" (NO, MAX_CAPACITY, INPATIENT_POSITION) VALUES (SEQ_INPATIENT_NO.NEXTVAL, '1', '1동 2층 201호');
INSERT INTO "C##ALLISWELL"."INPATIENT" (NO, MAX_CAPACITY, INPATIENT_POSITION) VALUES (SEQ_INPATIENT_NO.NEXTVAL, '1', '1동 2층 202호');
INSERT INTO "C##ALLISWELL"."INPATIENT" (NO, MAX_CAPACITY, INPATIENT_POSITION) VALUES (SEQ_INPATIENT_NO.NEXTVAL, '1', '1동 2층 203호');
INSERT INTO "C##ALLISWELL"."INPATIENT" (NO, MAX_CAPACITY, INPATIENT_POSITION) VALUES (SEQ_INPATIENT_NO.NEXTVAL, '4', '1동 3층 301호');
INSERT INTO "C##ALLISWELL"."INPATIENT" (NO, MAX_CAPACITY, INPATIENT_POSITION) VALUES (SEQ_INPATIENT_NO.NEXTVAL, '4', '1동 3층 302호');
INSERT INTO "C##ALLISWELL"."INPATIENT" (NO, MAX_CAPACITY, INPATIENT_POSITION) VALUES (SEQ_INPATIENT_NO.NEXTVAL, '4', '1동 3층 203호');
INSERT INTO "C##ALLISWELL"."INPATIENT" (NO, MAX_CAPACITY, INPATIENT_POSITION) VALUES (SEQ_INPATIENT_NO.NEXTVAL, '6', '1동 4층 401호');
INSERT INTO "C##ALLISWELL"."INPATIENT" (NO, MAX_CAPACITY, INPATIENT_POSITION) VALUES (SEQ_INPATIENT_NO.NEXTVAL, '6', '1동 4층 402호');
INSERT INTO "C##ALLISWELL"."INPATIENT" (NO, MAX_CAPACITY, INPATIENT_POSITION) VALUES (SEQ_INPATIENT_NO.NEXTVAL, '6', '1동 4층 403호');
INSERT INTO "C##ALLISWELL"."INPATIENT" (NO, MAX_CAPACITY, INPATIENT_POSITION) VALUES (SEQ_INPATIENT_NO.NEXTVAL, '6', '1동 4층 404호');


--ADMISSION_RECORD
INSERT INTO ADMISSION_RECORD(NO, PATIENT_NO, INPATIENT_NO, REASON, ADMISSION_DATE, DISCHARGE_DATE) VALUES(SEQ_ADMISSION_RECORD_NO.NEXTVAL, 1, 1, '간암 수술', TO_TIMESTAMP('2023-07-17 12:33:33'), TO_TIMESTAMP('2023-07-19 16:30:33'));
INSERT INTO ADMISSION_RECORD(NO, PATIENT_NO, INPATIENT_NO, REASON, ADMISSION_DATE, DISCHARGE_DATE) VALUES(SEQ_ADMISSION_RECORD_NO.NEXTVAL, 2, 2, '방광염 수술', TO_TIMESTAMP('2023-05-14 09:12:13'), TO_TIMESTAMP('2023-05-15 17:00:00'));
INSERT INTO ADMISSION_RECORD(NO, PATIENT_NO, INPATIENT_NO, REASON, ADMISSION_DATE, DISCHARGE_DATE) VALUES(SEQ_ADMISSION_RECORD_NO.NEXTVAL, 3, 3, '심장 수술', TO_TIMESTAMP('2023-05-15 10:55:17'), TO_TIMESTAMP('2023-05-19 18:25:25'));
INSERT INTO ADMISSION_RECORD(NO, PATIENT_NO, INPATIENT_NO, REASON, ADMISSION_DATE, DISCHARGE_DATE) VALUES(SEQ_ADMISSION_RECORD_NO.NEXTVAL, 4, 4, '직장암 수술', TO_TIMESTAMP('2023-03-09 09:00:00'), TO_TIMESTAMP('2023-03-10 16:30:33'));
INSERT INTO ADMISSION_RECORD(NO, PATIENT_NO, INPATIENT_NO, REASON, ADMISSION_DATE, DISCHARGE_DATE) VALUES(SEQ_ADMISSION_RECORD_NO.NEXTVAL, 5, 4, '교통사고', TO_TIMESTAMP('2023-01-01 11:05:10'), TO_TIMESTAMP('2023-01-03 15:10:20'));
INSERT INTO ADMISSION_RECORD(NO, PATIENT_NO, INPATIENT_NO, REASON, ADMISSION_DATE, DISCHARGE_DATE) VALUES(SEQ_ADMISSION_RECORD_NO.NEXTVAL, 6, 5, '추락사고', TO_TIMESTAMP('2022-12-12 12:12:12'), TO_TIMESTAMP('2022-12-15 15:25:35'));
INSERT INTO ADMISSION_RECORD(NO, PATIENT_NO, INPATIENT_NO, REASON, ADMISSION_DATE, DISCHARGE_DATE) VALUES(SEQ_ADMISSION_RECORD_NO.NEXTVAL, 7, 5, '디스크', TO_TIMESTAMP('2022-12-01 10:01:11'), TO_TIMESTAMP('2022-12-10 18:19:11'));
INSERT INTO ADMISSION_RECORD(NO, PATIENT_NO, INPATIENT_NO, REASON, ADMISSION_DATE, DISCHARGE_DATE) VALUES(SEQ_ADMISSION_RECORD_NO.NEXTVAL, 8, 5, '고혈압', TO_TIMESTAMP('2022-11-28 08:11:15'), TO_TIMESTAMP('2023-11-30 20:19:27'));
INSERT INTO ADMISSION_RECORD(NO, PATIENT_NO, INPATIENT_NO, REASON, ADMISSION_DATE, DISCHARGE_DATE) VALUES(SEQ_ADMISSION_RECORD_NO.NEXTVAL, 9, 5, '심근경색증', TO_TIMESTAMP('2022-11-17 22:29:10'), TO_TIMESTAMP('2022-11-19 16:11:55'));
INSERT INTO ADMISSION_RECORD(NO, PATIENT_NO, INPATIENT_NO, REASON, ADMISSION_DATE, DISCHARGE_DATE) VALUES(SEQ_ADMISSION_RECORD_NO.NEXTVAL, 10, 6, '빈혈', TO_TIMESTAMP('2022-10-05 11:37:28'), TO_TIMESTAMP('2022-10-20 18:19:27'));


--입원실 명단
INSERT INTO "C##ALLISWELL"."INPATIENT_LIST" (NO, INPATIENT_NO, PATIENT_NO) VALUES (SEQ_INPATIENT_LIST_NO.NEXTVAL, 1, 1);
INSERT INTO "C##ALLISWELL"."INPATIENT_LIST" (NO, INPATIENT_NO, PATIENT_NO) VALUES (SEQ_INPATIENT_LIST_NO.NEXTVAL, 2, 2);
INSERT INTO "C##ALLISWELL"."INPATIENT_LIST" (NO, INPATIENT_NO, PATIENT_NO) VALUES (SEQ_INPATIENT_LIST_NO.NEXTVAL, 3, 3);
INSERT INTO "C##ALLISWELL"."INPATIENT_LIST" (NO, INPATIENT_NO, PATIENT_NO) VALUES (SEQ_INPATIENT_LIST_NO.NEXTVAL, 4, 4);
INSERT INTO "C##ALLISWELL"."INPATIENT_LIST" (NO, INPATIENT_NO, PATIENT_NO) VALUES (SEQ_INPATIENT_LIST_NO.NEXTVAL, 4, 5);
INSERT INTO "C##ALLISWELL"."INPATIENT_LIST" (NO, INPATIENT_NO, PATIENT_NO) VALUES (SEQ_INPATIENT_LIST_NO.NEXTVAL, 5, 6);
INSERT INTO "C##ALLISWELL"."INPATIENT_LIST" (NO, INPATIENT_NO, PATIENT_NO) VALUES (SEQ_INPATIENT_LIST_NO.NEXTVAL, 5, 7);
INSERT INTO "C##ALLISWELL"."INPATIENT_LIST" (NO, INPATIENT_NO, PATIENT_NO) VALUES (SEQ_INPATIENT_LIST_NO.NEXTVAL, 5, 8);
INSERT INTO "C##ALLISWELL"."INPATIENT_LIST" (NO, INPATIENT_NO, PATIENT_NO) VALUES (SEQ_INPATIENT_LIST_NO.NEXTVAL, 5, 9);
INSERT INTO "C##ALLISWELL"."INPATIENT_LIST" (NO, INPATIENT_NO, PATIENT_NO) VALUES (SEQ_INPATIENT_LIST_NO.NEXTVAL, 6, 10);
--INSERT INTO "C##ALLISWELL"."INPATIENT_LIST" (NO, INPATIENT_NO, PATIENT_NO) VALUES (SEQ_INPATIENT_LIST_NO.NEXTVAL, '6', '11');
--INSERT INTO "C##ALLISWELL"."INPATIENT_LIST" (NO, INPATIENT_NO, PATIENT_NO) VALUES (SEQ_INPATIENT_LIST_NO.NEXTVAL, '6', '12');
--INSERT INTO "C##ALLISWELL"."INPATIENT_LIST" (NO, INPATIENT_NO, PATIENT_NO) VALUES (SEQ_INPATIENT_LIST_NO.NEXTVAL, '7', '13');
--INSERT INTO "C##ALLISWELL"."INPATIENT_LIST" (NO, INPATIENT_NO, PATIENT_NO) VALUES (SEQ_INPATIENT_LIST_NO.NEXTVAL, '7', '14');
--INSERT INTO "C##ALLISWELL"."INPATIENT_LIST" (NO, INPATIENT_NO, PATIENT_NO) VALUES (SEQ_INPATIENT_LIST_NO.NEXTVAL, '7', '15');
--INSERT INTO "C##ALLISWELL"."INPATIENT_LIST" (NO, INPATIENT_NO, PATIENT_NO) VALUES (SEQ_INPATIENT_LIST_NO.NEXTVAL, '7', '16');
--INSERT INTO "C##ALLISWELL"."INPATIENT_LIST" (NO, INPATIENT_NO, PATIENT_NO) VALUES (SEQ_INPATIENT_LIST_NO.NEXTVAL, '8', '17');
--INSERT INTO "C##ALLISWELL"."INPATIENT_LIST" (NO, INPATIENT_NO, PATIENT_NO) VALUES (SEQ_INPATIENT_LIST_NO.NEXTVAL, '8', '18');
--INSERT INTO "C##ALLISWELL"."INPATIENT_LIST" (NO, INPATIENT_NO, PATIENT_NO) VALUES (SEQ_INPATIENT_LIST_NO.NEXTVAL, '8', '19');
--INSERT INTO "C##ALLISWELL"."INPATIENT_LIST" (NO, INPATIENT_NO, PATIENT_NO) VALUES (SEQ_INPATIENT_LIST_NO.NEXTVAL, '8', '20');
--INSERT INTO "C##ALLISWELL"."INPATIENT_LIST" (NO, INPATIENT_NO, PATIENT_NO) VALUES (SEQ_INPATIENT_LIST_NO.NEXTVAL, '9', '21');
--INSERT INTO "C##ALLISWELL"."INPATIENT_LIST" (NO, INPATIENT_NO, PATIENT_NO) VALUES (SEQ_INPATIENT_LIST_NO.NEXTVAL, '9', '22');
--INSERT INTO "C##ALLISWELL"."INPATIENT_LIST" (NO, INPATIENT_NO, PATIENT_NO) VALUES (SEQ_INPATIENT_LIST_NO.NEXTVAL, '9', '23');
--INSERT INTO "C##ALLISWELL"."INPATIENT_LIST" (NO, INPATIENT_NO, PATIENT_NO) VALUES (SEQ_INPATIENT_LIST_NO.NEXTVAL, '9', '24');
--INSERT INTO "C##ALLISWELL"."INPATIENT_LIST" (NO, INPATIENT_NO, PATIENT_NO) VALUES (SEQ_INPATIENT_LIST_NO.NEXTVAL, '9', '25');
--INSERT INTO "C##ALLISWELL"."INPATIENT_LIST" (NO, INPATIENT_NO, PATIENT_NO) VALUES (SEQ_INPATIENT_LIST_NO.NEXTVAL, '10', '26');
--INSERT INTO "C##ALLISWELL"."INPATIENT_LIST" (NO, INPATIENT_NO, PATIENT_NO) VALUES (SEQ_INPATIENT_LIST_NO.NEXTVAL, '10', '27');
--INSERT INTO "C##ALLISWELL"."INPATIENT_LIST" (NO, INPATIENT_NO, PATIENT_NO) VALUES (SEQ_INPATIENT_LIST_NO.NEXTVAL, '10', '28');
--INSERT INTO "C##ALLISWELL"."INPATIENT_LIST" (NO, INPATIENT_NO, PATIENT_NO) VALUES (SEQ_INPATIENT_LIST_NO.NEXTVAL, '10', '29');
--INSERT INTO "C##ALLISWELL"."INPATIENT_LIST" (NO, INPATIENT_NO, PATIENT_NO) VALUES (SEQ_INPATIENT_LIST_NO.NEXTVAL, '10', '30');

--APPROVAL_DOCUMENT
INSERT INTO APPROVAL_DOCUMENT(NO, MEMBER_NO, CREATE_DATE, TITLE, STATUS) VALUES(SEQ_APPROVAL_DOCUMENT_NO.NEXTVAL, 1, TO_TIMESTAMP('2023-07-31 12:30:55'), '휴가문서', 'A');
INSERT INTO APPROVAL_DOCUMENT(NO, MEMBER_NO, CREATE_DATE, TITLE, STATUS) VALUES(SEQ_APPROVAL_DOCUMENT_NO.NEXTVAL, 2, TO_TIMESTAMP('2023-08-01 09:12:15'), '휴가문서', 'O');
INSERT INTO APPROVAL_DOCUMENT(NO, MEMBER_NO, CREATE_DATE, TITLE, STATUS) VALUES(SEQ_APPROVAL_DOCUMENT_NO.NEXTVAL, 3, TO_TIMESTAMP('2023-08-02 18:19:22'), '휴가문서', 'R');
INSERT INTO APPROVAL_DOCUMENT(NO, MEMBER_NO, CREATE_DATE, TITLE, STATUS) VALUES(SEQ_APPROVAL_DOCUMENT_NO.NEXTVAL, 4, TO_TIMESTAMP('2023-08-02 15:55:28'), '휴가문서', 'A');
INSERT INTO APPROVAL_DOCUMENT(NO, MEMBER_NO, CREATE_DATE, TITLE, STATUS) VALUES(SEQ_APPROVAL_DOCUMENT_NO.NEXTVAL, 11, TO_TIMESTAMP('2023-08-03 22:38:15'), '휴가문서', 'O');
INSERT INTO APPROVAL_DOCUMENT(NO, MEMBER_NO, CREATE_DATE, TITLE, STATUS) VALUES(SEQ_APPROVAL_DOCUMENT_NO.NEXTVAL, 6, TO_TIMESTAMP('2023-08-04 07:55:14'), '휴가문서', 'R');
INSERT INTO APPROVAL_DOCUMENT(NO, MEMBER_NO, CREATE_DATE, TITLE, STATUS) VALUES(SEQ_APPROVAL_DOCUMENT_NO.NEXTVAL, 7, TO_TIMESTAMP('2023-08-04 18:43:12'), '휴가문서', 'A');
INSERT INTO APPROVAL_DOCUMENT(NO, MEMBER_NO, CREATE_DATE, TITLE, STATUS) VALUES(SEQ_APPROVAL_DOCUMENT_NO.NEXTVAL, 8, TO_TIMESTAMP('2023-08-07 19:22:19'), '휴가문서', 'O');
INSERT INTO APPROVAL_DOCUMENT(NO, MEMBER_NO, CREATE_DATE, TITLE, STATUS) VALUES(SEQ_APPROVAL_DOCUMENT_NO.NEXTVAL, 9, TO_TIMESTAMP('2023-08-08 05:12:20'), '휴가문서', 'R');
INSERT INTO APPROVAL_DOCUMENT(NO, MEMBER_NO, CREATE_DATE, TITLE, STATUS) VALUES(SEQ_APPROVAL_DOCUMENT_NO.NEXTVAL, 10, TO_TIMESTAMP('2023-08-03 14:29:29'), '휴가문서', 'A');

INSERT INTO APPROVAL_DOCUMENT(NO, MEMBER_NO, CREATE_DATE, TITLE) VALUES(SEQ_APPROVAL_DOCUMENT_NO.NEXTVAL, 1, TO_TIMESTAMP('2023-07-31 12:30:55'), '출장문서');
INSERT INTO APPROVAL_DOCUMENT(NO, MEMBER_NO, CREATE_DATE, TITLE) VALUES(SEQ_APPROVAL_DOCUMENT_NO.NEXTVAL, 2, TO_TIMESTAMP('2023-08-01 12:30:55'), '출장문서');
INSERT INTO APPROVAL_DOCUMENT(NO, MEMBER_NO, CREATE_DATE, TITLE) VALUES(SEQ_APPROVAL_DOCUMENT_NO.NEXTVAL, 3, TO_TIMESTAMP('2023-08-02 12:30:55'), '출장문서');
INSERT INTO APPROVAL_DOCUMENT(NO, MEMBER_NO, CREATE_DATE, TITLE) VALUES(SEQ_APPROVAL_DOCUMENT_NO.NEXTVAL, 4, TO_TIMESTAMP('2023-08-03 12:30:55'), '출장문서');
INSERT INTO APPROVAL_DOCUMENT(NO, MEMBER_NO, CREATE_DATE, TITLE) VALUES(SEQ_APPROVAL_DOCUMENT_NO.NEXTVAL, 6, TO_TIMESTAMP('2023-08-04 12:30:55'), '출장문서');
INSERT INTO APPROVAL_DOCUMENT(NO, MEMBER_NO, CREATE_DATE, TITLE) VALUES(SEQ_APPROVAL_DOCUMENT_NO.NEXTVAL, 7, TO_TIMESTAMP('2023-08-09 12:30:55'), '출장문서');
INSERT INTO APPROVAL_DOCUMENT(NO, MEMBER_NO, CREATE_DATE, TITLE) VALUES(SEQ_APPROVAL_DOCUMENT_NO.NEXTVAL, 8, TO_TIMESTAMP('2023-08-10 12:30:55'), '출장문서');
INSERT INTO APPROVAL_DOCUMENT(NO, MEMBER_NO, CREATE_DATE, TITLE) VALUES(SEQ_APPROVAL_DOCUMENT_NO.NEXTVAL, 9, TO_TIMESTAMP('2023-08-07 12:30:55'), '출장문서');
INSERT INTO APPROVAL_DOCUMENT(NO, MEMBER_NO, CREATE_DATE, TITLE) VALUES(SEQ_APPROVAL_DOCUMENT_NO.NEXTVAL, 10, TO_TIMESTAMP('2023-08-07 12:30:55'), '출장문서');
INSERT INTO APPROVAL_DOCUMENT(NO, MEMBER_NO, CREATE_DATE, TITLE) VALUES(SEQ_APPROVAL_DOCUMENT_NO.NEXTVAL, 11, TO_TIMESTAMP('2023-08-08 12:30:55'), '출장문서');

INSERT INTO APPROVAL_DOCUMENT(NO, MEMBER_NO, CREATE_DATE, TITLE) VALUES(SEQ_APPROVAL_DOCUMENT_NO.NEXTVAL, 6, TO_TIMESTAMP('2023-07-31 12:30:55'), '재고신청문서');
INSERT INTO APPROVAL_DOCUMENT(NO, MEMBER_NO, CREATE_DATE, TITLE) VALUES(SEQ_APPROVAL_DOCUMENT_NO.NEXTVAL, 7, TO_TIMESTAMP('2023-08-01 12:30:55'), '재고신청문서');
INSERT INTO APPROVAL_DOCUMENT(NO, MEMBER_NO, CREATE_DATE, TITLE) VALUES(SEQ_APPROVAL_DOCUMENT_NO.NEXTVAL, 8, TO_TIMESTAMP('2023-08-02 12:30:55'), '재고신청문서');
INSERT INTO APPROVAL_DOCUMENT(NO, MEMBER_NO, CREATE_DATE, TITLE) VALUES(SEQ_APPROVAL_DOCUMENT_NO.NEXTVAL, 9, TO_TIMESTAMP('2023-08-03 12:30:55'), '재고신청문서');
INSERT INTO APPROVAL_DOCUMENT(NO, MEMBER_NO, CREATE_DATE, TITLE) VALUES(SEQ_APPROVAL_DOCUMENT_NO.NEXTVAL, 14, TO_TIMESTAMP('2023-08-04 12:30:55'), '재고신청문서');
INSERT INTO APPROVAL_DOCUMENT(NO, MEMBER_NO, CREATE_DATE, TITLE) VALUES(SEQ_APPROVAL_DOCUMENT_NO.NEXTVAL, 15, TO_TIMESTAMP('2023-08-07 12:30:55'), '재고신청문서');
INSERT INTO APPROVAL_DOCUMENT(NO, MEMBER_NO, CREATE_DATE, TITLE) VALUES(SEQ_APPROVAL_DOCUMENT_NO.NEXTVAL, 16, TO_TIMESTAMP('2023-08-08 12:30:55'), '재고신청문서');
INSERT INTO APPROVAL_DOCUMENT(NO, MEMBER_NO, CREATE_DATE, TITLE) VALUES(SEQ_APPROVAL_DOCUMENT_NO.NEXTVAL, 17, TO_TIMESTAMP('2023-08-09 12:30:55'), '재고신청문서');
INSERT INTO APPROVAL_DOCUMENT(NO, MEMBER_NO, CREATE_DATE, TITLE) VALUES(SEQ_APPROVAL_DOCUMENT_NO.NEXTVAL, 18, TO_TIMESTAMP('2023-08-10 12:30:55'), '재고신청문서');
INSERT INTO APPROVAL_DOCUMENT(NO, MEMBER_NO, CREATE_DATE, TITLE) VALUES(SEQ_APPROVAL_DOCUMENT_NO.NEXTVAL, 23, TO_TIMESTAMP('2023-08-11 12:30:55'), '재고신청문서');

--VACATION_APPROVAL_DOCUMENT
INSERT INTO VACATION_APPROVAL_DOCUMENT (NO, APPROVAL_DOCUMENT_NO, CONTENT, USE_DATE, START_DATE, END_DATE) VALUES (SEQ_VACATION_APPROVAL_DOCUMENT_NO.NEXTVAL, 1, '휴가', 2, '23/07/17', '23/07/19');
INSERT INTO VACATION_APPROVAL_DOCUMENT (NO, APPROVAL_DOCUMENT_NO, CONTENT, USE_DATE, START_DATE, END_DATE) VALUES (SEQ_VACATION_APPROVAL_DOCUMENT_NO.NEXTVAL, 2, '휴가', 2, '23/07/17', '23/07/19');
INSERT INTO VACATION_APPROVAL_DOCUMENT (NO, APPROVAL_DOCUMENT_NO, CONTENT, USE_DATE, START_DATE, END_DATE) VALUES (SEQ_VACATION_APPROVAL_DOCUMENT_NO.NEXTVAL, 3, '휴가', 2, '23/07/17', '23/07/19');
INSERT INTO VACATION_APPROVAL_DOCUMENT (NO, APPROVAL_DOCUMENT_NO, CONTENT, USE_DATE, START_DATE, END_DATE) VALUES (SEQ_VACATION_APPROVAL_DOCUMENT_NO.NEXTVAL, 4, '휴가', 2, '23/07/17', '23/07/19');
INSERT INTO VACATION_APPROVAL_DOCUMENT (NO, APPROVAL_DOCUMENT_NO, CONTENT, USE_DATE, START_DATE, END_DATE) VALUES (SEQ_VACATION_APPROVAL_DOCUMENT_NO.NEXTVAL, 5, '휴가', 2, '23/07/17', '23/07/19');
INSERT INTO VACATION_APPROVAL_DOCUMENT (NO, APPROVAL_DOCUMENT_NO, CONTENT, USE_DATE, START_DATE, END_DATE) VALUES (SEQ_VACATION_APPROVAL_DOCUMENT_NO.NEXTVAL, 6, '휴가', 2, '23/07/17', '23/07/19');
INSERT INTO VACATION_APPROVAL_DOCUMENT (NO, APPROVAL_DOCUMENT_NO, CONTENT, USE_DATE, START_DATE, END_DATE) VALUES (SEQ_VACATION_APPROVAL_DOCUMENT_NO.NEXTVAL, 7, '휴가', 2, '23/07/17', '23/07/19');
INSERT INTO VACATION_APPROVAL_DOCUMENT (NO, APPROVAL_DOCUMENT_NO, CONTENT, USE_DATE, START_DATE, END_DATE) VALUES (SEQ_VACATION_APPROVAL_DOCUMENT_NO.NEXTVAL, 8, '휴가', 2, '23/07/17', '23/07/19');
INSERT INTO VACATION_APPROVAL_DOCUMENT (NO, APPROVAL_DOCUMENT_NO, CONTENT, USE_DATE, START_DATE, END_DATE) VALUES (SEQ_VACATION_APPROVAL_DOCUMENT_NO.NEXTVAL, 9, '휴가', 2, '23/07/17', '23/07/19');
INSERT INTO VACATION_APPROVAL_DOCUMENT (NO, APPROVAL_DOCUMENT_NO, CONTENT, USE_DATE, START_DATE, END_DATE) VALUES (SEQ_VACATION_APPROVAL_DOCUMENT_NO.NEXTVAL, 10, '휴가', 2, '23/07/17', '23/07/19');

--재고종류
INSERT INTO "C##ALLISWELL"."INVENTORY_CATEGORY" (NO, ITEM_NAME) VALUES (SEQ_INVENTORY_CATEGORY_NO.NEXTVAL, '주사');
INSERT INTO "C##ALLISWELL"."INVENTORY_CATEGORY" (NO, ITEM_NAME) VALUES (SEQ_INVENTORY_CATEGORY_NO.NEXTVAL, '붕대');
INSERT INTO "C##ALLISWELL"."INVENTORY_CATEGORY" (NO, ITEM_NAME) VALUES (SEQ_INVENTORY_CATEGORY_NO.NEXTVAL, '링겔');
INSERT INTO "C##ALLISWELL"."INVENTORY_CATEGORY" (NO, ITEM_NAME) VALUES (SEQ_INVENTORY_CATEGORY_NO.NEXTVAL, '초음파');
INSERT INTO "C##ALLISWELL"."INVENTORY_CATEGORY" (NO, ITEM_NAME) VALUES (SEQ_INVENTORY_CATEGORY_NO.NEXTVAL, '거즈');
INSERT INTO "C##ALLISWELL"."INVENTORY_CATEGORY" (NO, ITEM_NAME) VALUES (SEQ_INVENTORY_CATEGORY_NO.NEXTVAL, '사체포');
INSERT INTO "C##ALLISWELL"."INVENTORY_CATEGORY" (NO, ITEM_NAME) VALUES (SEQ_INVENTORY_CATEGORY_NO.NEXTVAL, '카테터');
INSERT INTO "C##ALLISWELL"."INVENTORY_CATEGORY" (NO, ITEM_NAME) VALUES (SEQ_INVENTORY_CATEGORY_NO.NEXTVAL, '마스크');
INSERT INTO "C##ALLISWELL"."INVENTORY_CATEGORY" (NO, ITEM_NAME) VALUES (SEQ_INVENTORY_CATEGORY_NO.NEXTVAL, '소독겔');
INSERT INTO "C##ALLISWELL"."INVENTORY_CATEGORY" (NO, ITEM_NAME) VALUES (SEQ_INVENTORY_CATEGORY_NO.NEXTVAL, '메스');

--재고
INSERT INTO "C##ALLISWELL"."INVENTORY" (NO, CATEGORY_NO, INVENTORY_COUNT) VALUES (SEQ_INVENTORY_NO.NEXTVAL, '1', '20');
INSERT INTO "C##ALLISWELL"."INVENTORY" (NO, CATEGORY_NO, INVENTORY_COUNT) VALUES (SEQ_INVENTORY_NO.NEXTVAL, '2', '30');
INSERT INTO "C##ALLISWELL"."INVENTORY" (NO, CATEGORY_NO, INVENTORY_COUNT) VALUES (SEQ_INVENTORY_NO.NEXTVAL, '3', '40');
INSERT INTO "C##ALLISWELL"."INVENTORY" (NO, CATEGORY_NO, INVENTORY_COUNT) VALUES (SEQ_INVENTORY_NO.NEXTVAL, '4', '23');
INSERT INTO "C##ALLISWELL"."INVENTORY" (NO, CATEGORY_NO, INVENTORY_COUNT) VALUES (SEQ_INVENTORY_NO.NEXTVAL, '5', '35');
INSERT INTO "C##ALLISWELL"."INVENTORY" (NO, CATEGORY_NO, INVENTORY_COUNT) VALUES (SEQ_INVENTORY_NO.NEXTVAL, '6', '43');
INSERT INTO "C##ALLISWELL"."INVENTORY" (NO, CATEGORY_NO, INVENTORY_COUNT) VALUES (SEQ_INVENTORY_NO.NEXTVAL, '7', '12');
INSERT INTO "C##ALLISWELL"."INVENTORY" (NO, CATEGORY_NO, INVENTORY_COUNT) VALUES (SEQ_INVENTORY_NO.NEXTVAL, '8', '36');
INSERT INTO "C##ALLISWELL"."INVENTORY" (NO, CATEGORY_NO, INVENTORY_COUNT) VALUES (SEQ_INVENTORY_NO.NEXTVAL, '9', '65');
INSERT INTO "C##ALLISWELL"."INVENTORY" (NO, CATEGORY_NO, INVENTORY_COUNT) VALUES (SEQ_INVENTORY_NO.NEXTVAL, '10', '80');

--재고 신청 결재문서
INSERT INTO "C##ALLISWELL"."INVENTORY_REQUEST_APPROVAL_DOCUMENT" (NO, CATEGORY_NO, APPROVAL_DOCUMENT_NO, COUNT) VALUES (SEQ_INVENTORY_REQUEST_APPROVAL_DOCUMENT_NO.NEXTVAL, '1', '21', '10');
INSERT INTO "C##ALLISWELL"."INVENTORY_REQUEST_APPROVAL_DOCUMENT" (NO, CATEGORY_NO, APPROVAL_DOCUMENT_NO, COUNT) VALUES (SEQ_INVENTORY_REQUEST_APPROVAL_DOCUMENT_NO.NEXTVAL, '2', '22', '10');
INSERT INTO "C##ALLISWELL"."INVENTORY_REQUEST_APPROVAL_DOCUMENT" (NO, CATEGORY_NO, APPROVAL_DOCUMENT_NO, COUNT) VALUES (SEQ_INVENTORY_REQUEST_APPROVAL_DOCUMENT_NO.NEXTVAL, '3', '23', '10');
INSERT INTO "C##ALLISWELL"."INVENTORY_REQUEST_APPROVAL_DOCUMENT" (NO, CATEGORY_NO, APPROVAL_DOCUMENT_NO, COUNT) VALUES (SEQ_INVENTORY_REQUEST_APPROVAL_DOCUMENT_NO.NEXTVAL, '4', '24', '10');
INSERT INTO "C##ALLISWELL"."INVENTORY_REQUEST_APPROVAL_DOCUMENT" (NO, CATEGORY_NO, APPROVAL_DOCUMENT_NO, COUNT) VALUES (SEQ_INVENTORY_REQUEST_APPROVAL_DOCUMENT_NO.NEXTVAL, '5', '25', '10');
INSERT INTO "C##ALLISWELL"."INVENTORY_REQUEST_APPROVAL_DOCUMENT" (NO, CATEGORY_NO, APPROVAL_DOCUMENT_NO, COUNT) VALUES (SEQ_INVENTORY_REQUEST_APPROVAL_DOCUMENT_NO.NEXTVAL, '6', '26', '10');
INSERT INTO "C##ALLISWELL"."INVENTORY_REQUEST_APPROVAL_DOCUMENT" (NO, CATEGORY_NO, APPROVAL_DOCUMENT_NO, COUNT) VALUES (SEQ_INVENTORY_REQUEST_APPROVAL_DOCUMENT_NO.NEXTVAL, '7', '27', '10');
INSERT INTO "C##ALLISWELL"."INVENTORY_REQUEST_APPROVAL_DOCUMENT" (NO, CATEGORY_NO, APPROVAL_DOCUMENT_NO, COUNT) VALUES (SEQ_INVENTORY_REQUEST_APPROVAL_DOCUMENT_NO.NEXTVAL, '8', '28', '10');
INSERT INTO "C##ALLISWELL"."INVENTORY_REQUEST_APPROVAL_DOCUMENT" (NO, CATEGORY_NO, APPROVAL_DOCUMENT_NO, COUNT) VALUES (SEQ_INVENTORY_REQUEST_APPROVAL_DOCUMENT_NO.NEXTVAL, '9', '29', '10');
INSERT INTO "C##ALLISWELL"."INVENTORY_REQUEST_APPROVAL_DOCUMENT" (NO, CATEGORY_NO, APPROVAL_DOCUMENT_NO, COUNT) VALUES (SEQ_INVENTORY_REQUEST_APPROVAL_DOCUMENT_NO.NEXTVAL, '10', '30', '10');

--APPROVER
INSERT INTO APPROVER(NO, APPROVAL_DOCUMENT_NO, APPROVER_NO, APPROVAL_DATE, REASON, STATUS) VALUES(SEQ_APPROVER_NO.NEXTVAL, 1, 1, TO_TIMESTAMP('2023-07-17 19:28:35'), '사유가 정당함', 'F');
INSERT INTO APPROVER(NO, APPROVAL_DOCUMENT_NO, APPROVER_NO, APPROVAL_DATE, REASON, STATUS) VALUES(SEQ_APPROVER_NO.NEXTVAL, 2, 1, TO_TIMESTAMP('2023-06-27 11:45:10'), '사유가 불합리함', 'R');
INSERT INTO APPROVER(NO, APPROVAL_DOCUMENT_NO, APPROVER_NO, APPROVAL_DATE, REASON, STATUS) VALUES(SEQ_APPROVER_NO.NEXTVAL, 3, 1, TO_TIMESTAMP('2023-06-15 15:55:24'), '', 'W');
INSERT INTO APPROVER(NO, APPROVAL_DOCUMENT_NO, APPROVER_NO, APPROVAL_DATE, REASON, STATUS) VALUES(SEQ_APPROVER_NO.NEXTVAL, 4, 1, TO_TIMESTAMP('2023-05-05 21:18:39'), '너무 많이 씀', 'R');
INSERT INTO APPROVER(NO, APPROVAL_DOCUMENT_NO, APPROVER_NO, APPROVAL_DATE, REASON, STATUS) VALUES(SEQ_APPROVER_NO.NEXTVAL, 5, 1, TO_TIMESTAMP('2023-05-01 19:28:35'), '사유가 정당함', 'F');
INSERT INTO APPROVER(NO, APPROVAL_DOCUMENT_NO, APPROVER_NO, APPROVAL_DATE, REASON, STATUS) VALUES(SEQ_APPROVER_NO.NEXTVAL, 6, 1, TO_TIMESTAMP('2023-04-12 09:45:24'), '사유가 정당함', 'F');
INSERT INTO APPROVER(NO, APPROVAL_DOCUMENT_NO, APPROVER_NO, APPROVAL_DATE, REASON, STATUS) VALUES(SEQ_APPROVER_NO.NEXTVAL, 7, 1, TO_TIMESTAMP('2023-04-06 10:11:22'), '이유가 적합하지 않음', 'R');
INSERT INTO APPROVER(NO, APPROVAL_DOCUMENT_NO, APPROVER_NO, APPROVAL_DATE, REASON, STATUS) VALUES(SEQ_APPROVER_NO.NEXTVAL, 8, 1, TO_TIMESTAMP('2023-03-23 23:11:16'), '', 'W');
INSERT INTO APPROVER(NO, APPROVAL_DOCUMENT_NO, APPROVER_NO, APPROVAL_DATE, REASON, STATUS) VALUES(SEQ_APPROVER_NO.NEXTVAL, 9, 1, TO_TIMESTAMP('2023-03-15 11:28:39'), '사유가 정당함', 'F');
INSERT INTO APPROVER(NO, APPROVAL_DOCUMENT_NO, APPROVER_NO, APPROVAL_DATE, REASON, STATUS) VALUES(SEQ_APPROVER_NO.NEXTVAL, 10, 2, TO_TIMESTAMP('2023-03-03 03:33:33'), '별로임', 'W');

--BUSINESS_TRIP_APPROVAL_DOCUMENT
INSERT INTO BUSINESS_TRIP_APPROVAL_DOCUMENT(NO, APPROVAL_DOCUMENT_NO, CONTENT, START_DATE, END_DATE) VALUES(SEQ_BUSINESS_TRIP_APPROVAL_DOCUMENT_NO.NEXTVAL, 11, '미국 출장감', TO_TIMESTAMP('2023-07-17 00:00:00'), TO_TIMESTAMP('2023-07-25 00:00:00'));
INSERT INTO BUSINESS_TRIP_APPROVAL_DOCUMENT(NO, APPROVAL_DOCUMENT_NO, CONTENT, START_DATE, END_DATE) VALUES(SEQ_BUSINESS_TRIP_APPROVAL_DOCUMENT_NO.NEXTVAL, 12, '일본 출장감', TO_TIMESTAMP('2023-07-01 00:00:00'), TO_TIMESTAMP('2023-07-10 00:00:00'));
INSERT INTO BUSINESS_TRIP_APPROVAL_DOCUMENT(NO, APPROVAL_DOCUMENT_NO, CONTENT, START_DATE, END_DATE) VALUES(SEQ_BUSINESS_TRIP_APPROVAL_DOCUMENT_NO.NEXTVAL, 13, '뉴욕 출장감', TO_TIMESTAMP('2023-06-25 00:00:00'), TO_TIMESTAMP('2023-06-30 00:00:00'));
INSERT INTO BUSINESS_TRIP_APPROVAL_DOCUMENT(NO, APPROVAL_DOCUMENT_NO, CONTENT, START_DATE, END_DATE) VALUES(SEQ_BUSINESS_TRIP_APPROVAL_DOCUMENT_NO.NEXTVAL, 14, '싱가포르 출장감', TO_TIMESTAMP('2023-06-16 00:00:00'), TO_TIMESTAMP('2023-06-22 00:00:00'));
INSERT INTO BUSINESS_TRIP_APPROVAL_DOCUMENT(NO, APPROVAL_DOCUMENT_NO, CONTENT, START_DATE, END_DATE) VALUES(SEQ_BUSINESS_TRIP_APPROVAL_DOCUMENT_NO.NEXTVAL, 15, '인도네시아 출장감', TO_TIMESTAMP('2023-06-11 00:00:00'), TO_TIMESTAMP('2023-06-14 00:00:00'));
INSERT INTO BUSINESS_TRIP_APPROVAL_DOCUMENT(NO, APPROVAL_DOCUMENT_NO, CONTENT, START_DATE, END_DATE) VALUES(SEQ_BUSINESS_TRIP_APPROVAL_DOCUMENT_NO.NEXTVAL, 16, '중국 출장감', TO_TIMESTAMP('2023-05-12 00:00:00'), TO_TIMESTAMP('2023-05-25 00:00:00'));
INSERT INTO BUSINESS_TRIP_APPROVAL_DOCUMENT(NO, APPROVAL_DOCUMENT_NO, CONTENT, START_DATE, END_DATE) VALUES(SEQ_BUSINESS_TRIP_APPROVAL_DOCUMENT_NO.NEXTVAL, 17, '러시아 출장감', TO_TIMESTAMP('2023-05-05 00:00:00'), TO_TIMESTAMP('2023-05-10 00:00:00'));
INSERT INTO BUSINESS_TRIP_APPROVAL_DOCUMENT(NO, APPROVAL_DOCUMENT_NO, CONTENT, START_DATE, END_DATE) VALUES(SEQ_BUSINESS_TRIP_APPROVAL_DOCUMENT_NO.NEXTVAL, 18, '독일 출장감', TO_TIMESTAMP('2023-04-18 00:00:00'), TO_TIMESTAMP('2023-04-23 00:00:00'));
INSERT INTO BUSINESS_TRIP_APPROVAL_DOCUMENT(NO, APPROVAL_DOCUMENT_NO, CONTENT, START_DATE, END_DATE) VALUES(SEQ_BUSINESS_TRIP_APPROVAL_DOCUMENT_NO.NEXTVAL, 19, '영국 출장감', TO_TIMESTAMP('2023-03-24 00:00:00'), TO_TIMESTAMP('2023-03-29 00:00:00'));
INSERT INTO BUSINESS_TRIP_APPROVAL_DOCUMENT(NO, APPROVAL_DOCUMENT_NO, CONTENT, START_DATE, END_DATE) VALUES(SEQ_BUSINESS_TRIP_APPROVAL_DOCUMENT_NO.NEXTVAL, 20, '프랑스 출장감', TO_TIMESTAMP('2023-03-01 00:00:00'), TO_TIMESTAMP('2023-03-09 00:00:00'));


COMMIT;